import type { LearnedDiagnosticCase } from "../types/learning";

export const LEARNED_DIAGNOSTIC_CASES: LearnedDiagnosticCase[] = [
  {
    id: "learned_technical_builder_electric_practical_001",
    title: "Técnico eléctrico práctico que hace funcionar cosas reales",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Me gusta arreglar cosas, encontrar fallas, revisar instalaciones, probar hasta que funcione, cambiar piezas, mirar tableros, meter mano y dejar andando algo que no andaba.",
    expectedPrimaryFamily: "technical_builder",
    acceptableFamilies: ["technical_builder", "system_designer"],
    rivalFamilies: ["system_designer", "analytical_strategist"],
    keyHumanLanguage: [
      "arreglar cosas",
      "encontrar fallas",
      "probar hasta que funcione",
      "meter mano",
      "dejar andando",
      "no andaba",
      "instalaciones",
      "tableros",
    ],
    missingCuesDetected: [
      "dejar andando debe pesar como señal práctica/técnica",
      "meter mano debe empujar más a technical_builder que a system_designer",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando la persona habla de reparar, probar, meter mano y dejar funcionando algo real, el sistema debe mirar primero Technical Builder antes que System Designer.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_system_designer_architecture_001",
    title: "Diseñador de sistemas que piensa estructuras antes que ejecución",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Cuando veo un problema, no me interesa solamente arreglarlo rápido. Me interesa entender cómo está armado el sistema, qué piezas dependen de otras, qué flujo está mal diseñado y cómo evitar que vuelva a romperse.",
    expectedPrimaryFamily: "system_designer",
    acceptableFamilies: ["system_designer", "analytical_strategist"],
    rivalFamilies: ["technical_builder", "analytical_strategist"],
    keyHumanLanguage: [
      "cómo está armado el sistema",
      "piezas dependen de otras",
      "flujo mal diseñado",
      "evitar que vuelva a romperse",
      "diseñar estructura",
    ],
    missingCuesDetected: [
      "evitar que vuelva a romperse debe pesar como señal de diseño sistémico",
      "flujo mal diseñado debe empujar más a system_designer que a technical_builder",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando el foco está en arquitectura, dependencias, flujos y prevención estructural, debe pesar System Designer por encima de Technical Builder.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_creative_storyteller_no_public_front_001",
    title: "Relato y forma narrativa sin deseo de escena pública",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Me gusta escribir, editar, encontrar el tono, darle forma a una idea y volver texto algo que estaba suelto. No sé si quiero estar al frente ni poner la cara; me interesa más la forma que ocupar una voz pública.",
    expectedPrimaryFamily: "creative_storyteller",
    acceptableFamilies: ["creative_storyteller", "public_communicator"],
    rivalFamilies: ["public_communicator", "educator_interpreter"],
    keyHumanLanguage: [
      "escribir",
      "editar",
      "encontrar el tono",
      "darle forma",
      "volver texto",
      "no quiero estar al frente",
      "no poner la cara",
      "me interesa más la forma",
    ],
    missingCuesDetected: [
      "rechazo del frente público debe bajar public_communicator",
      "interés por forma, tono y texto debe sostener creative_storyteller",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando hay escritura, edición, tono y forma narrativa con rechazo explícito del frente público, Creative Storyteller debe quedar por encima o al menos empatado con Public Communicator.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_public_communicator_stance_001",
    title: "Voz pública con postura y necesidad de decir",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Cuando un tema me importa, necesito tomar postura, ordenar lo que está en juego y decirlo claro para otros. No escribo sólo por escribir: me interesa fijar posición y mover una conversación pública.",
    expectedPrimaryFamily: "public_communicator",
    acceptableFamilies: ["public_communicator", "creative_storyteller"],
    rivalFamilies: ["creative_storyteller", "educator_interpreter"],
    keyHumanLanguage: [
      "tomar postura",
      "qué está en juego",
      "decirlo claro para otros",
      "fijar posición",
      "conversación pública",
      "tema me importa",
    ],
    missingCuesDetected: [
      "tomar postura debe empujar a public_communicator",
      "conversación pública debe pesar más que escritura genérica",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando la escritura está al servicio de postura, agenda, tema público o intervención hacia otros, Public Communicator debe superar a Creative Storyteller.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_empathic_guide_one_to_one_001",
    title: "Acompañamiento uno a uno, no coordinación grupal",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "La gente me termina contando cosas. Me sale escuchar, hacer preguntas, ayudar a que alguien ordene lo que le pasa y acompañar sin invadir. No soy tanto de armar grupos ni de mediar entre sectores.",
    expectedPrimaryFamily: "empathic_guide",
    acceptableFamilies: ["empathic_guide"],
    rivalFamilies: ["community_builder", "diplomatic_social_connector"],
    keyHumanLanguage: [
      "me cuentan cosas",
      "escuchar",
      "hacer preguntas",
      "ordenar lo que le pasa",
      "acompañar sin invadir",
      "no soy tanto de armar grupos",
      "no mediar entre sectores",
    ],
    missingCuesDetected: [
      "acompañamiento uno a uno debe pesar más que coordinación grupal",
      "rechazo de armar grupos debe bajar community_builder",
      "rechazo de mediar entre sectores debe bajar diplomatic_social_connector",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando el objeto es una persona individual y su mundo interno, debe pesar Empathic Guide más que Community Builder o Diplomatic Social Connector.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_diplomatic_connector_multi_actor_001",
    title: "Puente entre partes, actores o áreas",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Siempre termino en el medio cuando hay áreas, personas o intereses cruzados. Hablo con uno, con otro, leo qué necesita cada parte y destrabo para que puedan avanzar sin romperse.",
    expectedPrimaryFamily: "diplomatic_social_connector",
    acceptableFamilies: ["diplomatic_social_connector", "institutional_operator"],
    rivalFamilies: ["empathic_guide", "community_builder"],
    keyHumanLanguage: [
      "en el medio",
      "áreas",
      "intereses cruzados",
      "hablo con uno y con otro",
      "cada parte",
      "destrabo",
      "avanzar sin romperse",
    ],
    missingCuesDetected: [
      "intereses cruzados debe pesar como mediación entre partes",
      "destrabar entre áreas debe empujar a diplomatic_social_connector",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando el foco está en varias partes, intereses cruzados y destrabe relacional, debe pesar Diplomatic Social Connector más que Empathic Guide.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_technical_builder_ex_bancario_motores_001",
    title: "Ex bancario con deseo técnico-práctico ligado a motores y autos",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Trabajo en un banco desde hace años, pero estoy harto y quiero salir para hacer algo que me guste. De chico jugaba con autitos de carrera, armaba pistas, desarmaba y armaba cosas. Me gustaba hacer que motores a pila funcionen. En mis ratos libres leo sobre componentes mecánicos y eléctricos de autos de carrera. Me veo más en un taller armando motores que estando en un banco. Tengo conocimiento por cursos técnicos y quiero recibir autos de carrera para incorporar motores adicionales y elementos electrónicos.",
    expectedPrimaryFamily: "technical_builder",
    acceptableFamilies: ["technical_builder", "system_designer"],
    rivalFamilies: [
      "system_designer",
      "analytical_strategist",
      "institutional_operator",
    ],
    keyHumanLanguage: [
      "desarmaba y armaba cosas",
      "hacer que motores funcionen",
      "motores a pila",
      "componentes mecánicos",
      "componentes eléctricos",
      "autos de carrera",
      "taller",
      "armando motores",
      "cursos técnicos",
      "elementos electrónicos",
      "salir del banco",
    ],
    missingCuesDetected: [
      "motores debe pesar como señal técnica-práctica",
      "desarmar y armar cosas debe activar Technical Builder",
      "taller debe empujar más a Technical Builder que a System Designer",
      "componentes mecánicos y eléctricos deben contar como evidencia técnica concreta",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando una persona expresa deseo sostenido de desarmar, armar, reparar, hacer funcionar motores, trabajar con componentes mecánicos/eléctricos y verse en un taller, Technical Builder debe aparecer como hipótesis principal o al menos como hipótesis asistida por aprendizaje, aunque el motor principal no detecte suficiente evidencia.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_creative_storyteller_educator_frontier_001",
    title: "Escritura, relato y explicación clara como frontera vocacional",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText: [
      "Trabajo en una oficina hace años, pero siento que me apago.",
      "Lo que más me sale naturalmente es escribir, explicar ideas, armar textos, contar historias y encontrar una forma clara de decir cosas que otros no logran expresar.",
      "Me gustaba inventar historias, escribir diálogos, hacer revistas caseras y preparar pequeñas actuaciones para mi familia.",
      "Me atraía cómo una frase podía cambiar la forma en que alguien entendía algo.",
      "Siempre termino redactando mensajes, ordenando presentaciones, corrigiendo textos o ayudando a otros a decir mejor lo que quieren decir.",
      "Suelo ser quien pone en palabras lo que está dando vueltas.",
      "Dejé de escribir, de armar contenido y de mostrar ideas propias porque sentía que eso no era serio o no daba plata.",
      "Mi voz propia está comprimida.",
      "Me gustaría dedicarme a comunicar, escribir, hacer contenido o contar historias con sentido.",
    ].join(" "),
    expectedPrimaryFamily: "creative_storyteller",
    acceptableFamilies: ["creative_storyteller", "educator_interpreter"],
    rivalFamilies: ["public_communicator", "cultural_explorer"],
    keyHumanLanguage: [
      "escribir",
      "explicar ideas",
      "armar textos",
      "contar historias",
      "forma clara de decir",
      "inventar historias",
      "escribir diálogos",
      "revistas caseras",
      "frase",
      "entendía algo",
      "redactando mensajes",
      "corrigiendo textos",
      "poner en palabras",
      "voz propia",
      "comunicar",
      "contenido",
      "relatos útiles",
    ],
    missingCuesDetected: [
      "escribir, contar historias y armar textos deben sostener Creative Storyteller",
      "explicar ideas y ayudar a otros a comprender deben abrir frontera con Educator Interpreter",
      "comunicar o contenido no deben activar automáticamente Public Communicator si no hay postura pública, audiencia, agenda o intervención social explícita",
      "voz propia comprimida debe leerse como capacidad expresiva enterrada, no como mera preferencia superficial",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando una persona muestra deseo sostenido de escribir, contar historias, armar textos, encontrar forma verbal y poner en palabras lo que otros no logran expresar, Creative Storyteller debe quedar muy alto. Si además aparece impulso de explicar ideas para que otros comprendan, Educator Interpreter debe aparecer como frontera aceptable. No debe confundirse automáticamente con Public Communicator si no hay audiencia pública, postura, agenda o intervención social explícita.",
    shouldInfluenceFutureCases: true,
  },
    {
      id: "learned_public_communicator_public_stance_002",
      title: "Comunicación pública con postura, agenda y audiencia",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Me pasa que cuando veo un tema social o político mal explicado, necesito ordenar qué está pasando, tomar postura y decirlo públicamente. No me alcanza con escribir algo lindo: quiero que el texto sirva para mover una conversación, instalar una idea o discutir una mirada. Me imagino escribiendo columnas, haciendo editoriales, armando hilos, hablando en radio o generando contenido donde haya una posición clara frente a una audiencia.",
      expectedPrimaryFamily: "public_communicator",
      acceptableFamilies: ["public_communicator", "civic_advocate"],
      rivalFamilies: ["creative_storyteller", "educator_interpreter"],
      keyHumanLanguage: [
        "tema social",
        "tema político",
        "tomar postura",
        "decirlo públicamente",
        "mover una conversación",
        "instalar una idea",
        "discutir una mirada",
        "columnas",
        "editoriales",
        "hilos",
        "radio",
        "contenido",
        "posición clara",
        "audiencia",
      ],
      missingCuesDetected: [
        "tomar postura debe pesar más hacia Public Communicator que hacia Creative Storyteller",
        "audiencia explícita debe activar lectura pública",
        "instalar una idea debe contar como señal de agenda pública",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando la escritura aparece al servicio de postura, agenda, intervención pública, audiencia explícita o discusión colectiva, Public Communicator debe pesar por encima de Creative Storyteller. La forma narrativa puede estar presente, pero no debe dominar si el objeto principal es intervenir en conversación pública.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_educator_interpreter_clarity_for_others_002",
      title: "Explicar para que otros comprendan mejor",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Siempre termino explicando cosas. En el trabajo, cuando alguien no entiende un proceso, me sale desarmarlo en partes, buscar ejemplos simples y traducirlo a un lenguaje que la otra persona pueda entender. Me gusta cuando alguien me dice 'ahora sí lo entendí'. No necesito estar al frente de una causa ni tener una voz pública: lo que más me importa es ayudar a que otros comprendan algo que parecía confuso.",
      expectedPrimaryFamily: "educator_interpreter",
      acceptableFamilies: ["educator_interpreter", "empathic_guide"],
      rivalFamilies: ["public_communicator", "creative_storyteller", "analytical_strategist"],
      keyHumanLanguage: [
        "explicando cosas",
        "alguien no entiende",
        "desarmarlo en partes",
        "ejemplos simples",
        "traducirlo",
        "lenguaje que la otra persona pueda entender",
        "ahora sí lo entendí",
        "ayudar a que otros comprendan",
        "confuso",
      ],
      missingCuesDetected: [
        "explicar para comprensión ajena debe pesar más hacia Educator Interpreter",
        "traducir complejidad a lenguaje simple no debe confundirse automáticamente con Public Communicator",
        "no necesitar voz pública debe reducir adjudicación pública",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando el centro del relato es traducir complejidad para que otros comprendan, usando ejemplos, partes, claridad y adaptación al receptor, Educator Interpreter debe pesar por encima de Public Communicator y Creative Storyteller. La clave no es expresarse ni tomar postura, sino producir comprensión en otros.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_creative_storyteller_private_voice_002",
      title: "Voz narrativa propia sin agenda pública",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Desde chico me gustó inventar escenas, escribir diálogos, imaginar personajes y encontrar una forma propia de contar lo que me pasa. A veces escribo textos que no publico, sólo porque necesito darles forma. Me interesa el tono, la atmósfera, la frase justa, la emoción que queda después de leer algo. No pienso tanto en convencer a una audiencia ni en explicar un tema: me interesa construir una voz y transformar experiencias en relato.",
      expectedPrimaryFamily: "creative_storyteller",
      acceptableFamilies: ["creative_storyteller"],
      rivalFamilies: ["public_communicator", "educator_interpreter", "cultural_explorer"],
      keyHumanLanguage: [
        "inventar escenas",
        "escribir diálogos",
        "imaginar personajes",
        "forma propia de contar",
        "textos que no publico",
        "darles forma",
        "tono",
        "atmósfera",
        "frase justa",
        "emoción",
        "construir una voz",
        "transformar experiencias en relato",
      ],
      missingCuesDetected: [
        "textos que no publico debe reducir Public Communicator",
        "tono, atmósfera y frase justa deben pesar hacia Creative Storyteller",
        "transformar experiencia en relato debe activar núcleo narrativo",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando la persona habla de voz propia, escenas, diálogos, tono, atmósfera, frase justa y transformación de experiencia en relato, Creative Storyteller debe pesar con fuerza. Si no hay audiencia, postura, agenda pública ni intención de enseñar, no debe arrastrarse automáticamente hacia Public Communicator o Educator Interpreter.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_public_communicator_educator_frontier_001",
      title: "Comunicación pública que también busca explicar",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Me gusta agarrar temas difíciles de actualidad, ordenarlos y explicarlos para que más gente entienda qué está pasando. Pero no lo haría como una clase neutra: también me importa señalar qué está en juego, marcar una posición y ayudar a que otros puedan mirar el tema de otra manera. Me imagino haciendo videos, columnas o charlas donde combino explicación clara con postura pública.",
      expectedPrimaryFamily: "public_communicator",
      acceptableFamilies: ["public_communicator", "educator_interpreter"],
      rivalFamilies: ["creative_storyteller", "civic_advocate"],
      keyHumanLanguage: [
        "temas difíciles de actualidad",
        "ordenarlos",
        "explicarlos",
        "más gente entienda",
        "qué está pasando",
        "no como una clase neutra",
        "qué está en juego",
        "marcar una posición",
        "mirar el tema de otra manera",
        "videos",
        "columnas",
        "charlas",
        "explicación clara",
        "postura pública",
      ],
      missingCuesDetected: [
        "explicación clara más postura pública debe abrir frontera Public Communicator / Educator Interpreter",
        "actualidad, posición y audiencia deben sostener Public Communicator",
        "comprensión ajena debe sostener Educator Interpreter como familia aceptable",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando una persona combina explicación clara para otros con postura pública, actualidad, audiencia y señalamiento de lo que está en juego, el sistema debe abrir una frontera Public Communicator / Educator Interpreter. Si la postura y la audiencia son explícitas, Public Communicator puede quedar primero, pero Educator Interpreter debe permanecer como familia aceptable fuerte.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_public_communicator_editorial_agenda_001",
      title: "Comunicación pública con agenda, audiencia y postura editorial",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Me pasa que cuando veo un tema social o político importante necesito ordenarlo, tomar postura y escribir algo que otros puedan leer. No me alcanza con entenderlo para mí: quiero convertirlo en una explicación pública, con una mirada clara, una agenda y una voz que pueda circular. Me interesan las columnas, editoriales, hilos, programas o espacios donde una idea pueda influir en una conversación más amplia.",
      expectedPrimaryFamily: "public_communicator",
      acceptableFamilies: ["public_communicator", "educator_interpreter"],
      rivalFamilies: [
        "creative_storyteller",
        "civic_advocate",
        "institutional_operator",
      ],
      keyHumanLanguage: [
        "tema social",
        "tema político",
        "tomar postura",
        "explicación pública",
        "mirada clara",
        "agenda",
        "voz que pueda circular",
        "columnas",
        "editoriales",
        "hilos",
        "programas",
        "conversación más amplia",
      ],
      missingCuesDetected: [
        "tomar postura y agenda deben pesar como señal fuerte de Public Communicator",
        "audiencia o circulación pública deben diferenciar Public Communicator de Creative Storyteller",
        "explicar públicamente puede apoyar Educator Interpreter, pero no debe desplazar Public Communicator si hay postura y audiencia",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando la persona habla de temas sociales o políticos, toma postura, construye agenda, busca audiencia y quiere intervenir en una conversación pública, Public Communicator debe pesar por encima de Creative Storyteller y Educator Interpreter. Educator Interpreter puede quedar como familia aceptable si hay explicación clara para otros.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_educator_interpreter_clear_explanation_no_public_agenda_001",
      title: "Explicación clara para comprensión ajena sin agenda pública",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Me gusta agarrar temas difíciles y hacerlos entendibles. Si alguien no comprende algo, trato de buscar ejemplos, ordenar la idea paso por paso y traducirlo a un lenguaje más simple. No necesariamente quiero opinar en público ni instalar una agenda; lo que más me importa es que la otra persona finalmente entienda.",
      expectedPrimaryFamily: "educator_interpreter",
      acceptableFamilies: ["educator_interpreter"],
      rivalFamilies: [
        "public_communicator",
        "creative_storyteller",
        "analytical_strategist",
      ],
      keyHumanLanguage: [
        "temas difíciles",
        "hacerlos entendibles",
        "buscar ejemplos",
        "ordenar la idea paso por paso",
        "traducirlo a un lenguaje más simple",
        "no quiero opinar en público",
        "no instalar una agenda",
        "que la otra persona entienda",
      ],
      missingCuesDetected: [
        "explicar para que otro comprenda debe activar Educator Interpreter",
        "no querer opinar en público debe limitar Public Communicator",
        "ordenar paso a paso no debe convertirse automáticamente en Analytical Strategist si el destino es comprensión ajena",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando el foco principal es traducir complejidad para que otra persona comprenda, sin agenda pública, postura ni audiencia amplia, Educator Interpreter debe quedar por encima de Public Communicator y Creative Storyteller.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_civic_advocate_cause_pressure_001",
      title: "Incidencia cívica con causa, presión y cambio concreto",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Cuando veo una injusticia o un problema colectivo, me cuesta quedarme quieto. Pienso en cómo denunciarlo, juntar gente, presionar a quienes tienen responsabilidad y lograr que algo cambie. Puedo escribir o hablar en público, pero no es sólo comunicar: me interesa empujar una causa, incomodar si hace falta y conseguir una respuesta concreta.",
      expectedPrimaryFamily: "civic_advocate",
      acceptableFamilies: ["civic_advocate", "public_communicator"],
      rivalFamilies: [
        "public_communicator",
        "diplomatic_social_connector",
        "institutional_operator",
      ],
      keyHumanLanguage: [
        "injusticia",
        "problema colectivo",
        "denunciarlo",
        "juntar gente",
        "presionar",
        "responsabilidad",
        "lograr que algo cambie",
        "empujar una causa",
        "incomodar",
        "respuesta concreta",
      ],
      missingCuesDetected: [
        "injusticia, causa y presión deben activar Civic Advocate",
        "hablar o escribir en público no alcanza para Public Communicator si el centro es incidencia y cambio",
        "presionar responsables no debe confundirse con Diplomatic Social Connector si no hay mediación sino exigencia",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando la comunicación está al servicio de una causa, denuncia, presión pública o cambio colectivo concreto, Civic Advocate debe pesar más que Public Communicator. Public Communicator puede quedar como familia aceptable si hay voz pública fuerte.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_institutional_operator_formal_navigation_001",
      title: "Operador institucional que entiende reglas, áreas y procedimientos",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "En los trabajos donde mejor me muevo es cuando hay reglas, expedientes, áreas, jerarquías y procedimientos. Suelo entender rápido quién decide qué, qué paso falta, qué norma hay que mirar y cómo hacer avanzar algo dentro de una estructura formal. No busco necesariamente hablarle al público ni levantar una causa; me interesa que el trámite, el circuito o la institución funcionen.",
      expectedPrimaryFamily: "institutional_operator",
      acceptableFamilies: ["institutional_operator", "diplomatic_social_connector"],
      rivalFamilies: [
        "public_communicator",
        "civic_advocate",
        "analytical_strategist",
      ],
      keyHumanLanguage: [
        "reglas",
        "expedientes",
        "áreas",
        "jerarquías",
        "procedimientos",
        "quién decide qué",
        "qué paso falta",
        "qué norma",
        "estructura formal",
        "trámite",
        "circuito",
        "institución",
      ],
      missingCuesDetected: [
        "reglas, expedientes, jerarquías y procedimientos deben activar Institutional Operator",
        "institución no debe empujar automáticamente a Civic Advocate si no hay causa o presión pública",
        "áreas y estructura formal pueden apoyar Diplomatic Social Connector sólo si hay articulación entre partes",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando la persona se orienta por reglas, procedimientos, jerarquías, expedientes, circuitos y funcionamiento interno de una estructura formal, Institutional Operator debe pesar por encima de Public Communicator o Civic Advocate, salvo que aparezcan audiencia pública, causa o presión social explícita.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_diplomatic_social_connector_between_actors_001",
      title: "Conector diplomático entre actores con intereses distintos",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Muchas veces termino siendo quien habla con una parte y con la otra. Me doy cuenta de qué necesita cada actor, qué le molesta a cada lado y dónde se puede destrabar la conversación. No me interesa tanto denunciar ni tomar postura pública; prefiero encontrar un punto de acuerdo para que las partes puedan avanzar sin romper la relación.",
      expectedPrimaryFamily: "diplomatic_social_connector",
      acceptableFamilies: [
        "diplomatic_social_connector",
        "institutional_operator",
      ],
      rivalFamilies: [
        "civic_advocate",
        "public_communicator",
        "empathic_guide",
      ],
      keyHumanLanguage: [
        "una parte y la otra",
        "cada actor",
        "cada lado",
        "destrabar la conversación",
        "no denunciar",
        "no tomar postura pública",
        "punto de acuerdo",
        "las partes",
        "avanzar sin romper la relación",
      ],
      missingCuesDetected: [
        "partes, actores, lados y acuerdo deben activar Diplomatic Social Connector",
        "no denunciar y no tomar postura pública deben limitar Civic Advocate y Public Communicator",
        "acompañar vínculos entre partes no debe confundirse con Empathic Guide si el objeto no es una persona individual sino una relación entre actores",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando el foco está en leer actores, destrabar conversaciones, cuidar relaciones y encontrar acuerdos entre partes distintas, Diplomatic Social Connector debe pesar por encima de Civic Advocate, Public Communicator y Empathic Guide.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_public_communicator_vs_institutional_boundary_001",
      title: "Comunicación sobre instituciones sin operación institucional directa",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Me interesa explicar cómo funcionan las instituciones, qué decisiones se toman, qué intereses aparecen y cómo eso afecta a la gente. Pero no me imagino haciendo expedientes ni llevando circuitos internos. Me veo más escribiendo, hablando o armando análisis para una audiencia que necesita entender lo que pasa dentro del poder.",
      expectedPrimaryFamily: "public_communicator",
      acceptableFamilies: [
        "public_communicator",
        "educator_interpreter",
        "institutional_operator",
      ],
      rivalFamilies: [
        "institutional_operator",
        "civic_advocate",
        "analytical_strategist",
      ],
      keyHumanLanguage: [
        "explicar cómo funcionan las instituciones",
        "decisiones",
        "intereses",
        "afecta a la gente",
        "no expedientes",
        "no circuitos internos",
        "escribiendo",
        "hablando",
        "análisis para una audiencia",
        "entender lo que pasa dentro del poder",
      ],
      missingCuesDetected: [
        "hablar sobre instituciones no debe activar automáticamente Institutional Operator",
        "si el destino es audiencia y explicación pública, Public Communicator debe pesar más que Institutional Operator",
        "Educator Interpreter puede quedar como apoyo si el foco es hacer comprensible la complejidad institucional",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando la persona interpreta instituciones para una audiencia, sin interés en operar expedientes, normas o circuitos internos, Public Communicator debe pesar por encima de Institutional Operator. Institutional Operator puede quedar como familia aceptable sólo por contenido institucional, no como dirección principal.",
      shouldInfluenceFutureCases: true,
    },
];