import type { LearnedDiagnosticCase } from "../types/learning";

export const LEARNED_DIAGNOSTIC_CASES: LearnedDiagnosticCase[] = [
  {
    id: "learned_technical_builder_electric_practical_001",
    title: "Técnico eléctrico práctico que hace funcionar cosas reales",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Me gusta arreglar cosas, encontrar fallas, revisar instalaciones, probar hasta que funcione, cambiar piezas, mirar tableros, meter mano y dejar andando algo que no andaba.",
    expectedPrimaryFamily: "technical_builder",
    acceptableFamilies: ["technical_builder", "system_designer"],
    rivalFamilies: ["system_designer", "analytical_strategist"],
    keyHumanLanguage: [
      "arreglar cosas",
      "encontrar fallas",
      "probar hasta que funcione",
      "meter mano",
      "dejar andando",
      "no andaba",
      "instalaciones",
      "tableros",
    ],
    missingCuesDetected: [
      "dejar andando debe pesar como señal práctica/técnica",
      "meter mano debe empujar más a technical_builder que a system_designer",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando la persona habla de reparar, probar, meter mano y dejar funcionando algo real, el sistema debe mirar primero Technical Builder antes que System Designer.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_system_designer_architecture_001",
    title: "Diseñador de sistemas que piensa estructuras antes que ejecución",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Cuando veo un problema, no me interesa solamente arreglarlo rápido. Me interesa entender cómo está armado el sistema, qué piezas dependen de otras, qué flujo está mal diseñado y cómo evitar que vuelva a romperse.",
    expectedPrimaryFamily: "system_designer",
    acceptableFamilies: ["system_designer", "analytical_strategist"],
    rivalFamilies: ["technical_builder", "analytical_strategist"],
    keyHumanLanguage: [
      "cómo está armado el sistema",
      "piezas dependen de otras",
      "flujo mal diseñado",
      "evitar que vuelva a romperse",
      "diseñar estructura",
    ],
    missingCuesDetected: [
      "evitar que vuelva a romperse debe pesar como señal de diseño sistémico",
      "flujo mal diseñado debe empujar más a system_designer que a technical_builder",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando el foco está en arquitectura, dependencias, flujos y prevención estructural, debe pesar System Designer por encima de Technical Builder.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_creative_storyteller_no_public_front_001",
    title: "Relato y forma narrativa sin deseo de escena pública",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Me gusta escribir, editar, encontrar el tono, darle forma a una idea y volver texto algo que estaba suelto. No sé si quiero estar al frente ni poner la cara; me interesa más la forma que ocupar una voz pública.",
    expectedPrimaryFamily: "creative_storyteller",
    acceptableFamilies: ["creative_storyteller", "public_communicator"],
    rivalFamilies: ["public_communicator", "educator_interpreter"],
    keyHumanLanguage: [
      "escribir",
      "editar",
      "encontrar el tono",
      "darle forma",
      "volver texto",
      "no quiero estar al frente",
      "no poner la cara",
      "me interesa más la forma",
    ],
    missingCuesDetected: [
      "rechazo del frente público debe bajar public_communicator",
      "interés por forma, tono y texto debe sostener creative_storyteller",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando hay escritura, edición, tono y forma narrativa con rechazo explícito del frente público, Creative Storyteller debe quedar por encima o al menos empatado con Public Communicator.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_public_communicator_stance_001",
    title: "Voz pública con postura y necesidad de decir",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Cuando un tema me importa, necesito tomar postura, ordenar lo que está en juego y decirlo claro para otros. No escribo sólo por escribir: me interesa fijar posición y mover una conversación pública.",
    expectedPrimaryFamily: "public_communicator",
    acceptableFamilies: ["public_communicator", "creative_storyteller"],
    rivalFamilies: ["creative_storyteller", "educator_interpreter"],
    keyHumanLanguage: [
      "tomar postura",
      "qué está en juego",
      "decirlo claro para otros",
      "fijar posición",
      "conversación pública",
      "tema me importa",
    ],
    missingCuesDetected: [
      "tomar postura debe empujar a public_communicator",
      "conversación pública debe pesar más que escritura genérica",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando la escritura está al servicio de postura, agenda, tema público o intervención hacia otros, Public Communicator debe superar a Creative Storyteller.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_empathic_guide_one_to_one_001",
    title: "Acompañamiento uno a uno, no coordinación grupal",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "La gente me termina contando cosas. Me sale escuchar, hacer preguntas, ayudar a que alguien ordene lo que le pasa y acompañar sin invadir. No soy tanto de armar grupos ni de mediar entre sectores.",
    expectedPrimaryFamily: "empathic_guide",
    acceptableFamilies: ["empathic_guide"],
    rivalFamilies: ["community_builder", "diplomatic_social_connector"],
    keyHumanLanguage: [
      "me cuentan cosas",
      "escuchar",
      "hacer preguntas",
      "ordenar lo que le pasa",
      "acompañar sin invadir",
      "no soy tanto de armar grupos",
      "no mediar entre sectores",
    ],
    missingCuesDetected: [
      "acompañamiento uno a uno debe pesar más que coordinación grupal",
      "rechazo de armar grupos debe bajar community_builder",
      "rechazo de mediar entre sectores debe bajar diplomatic_social_connector",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando el objeto es una persona individual y su mundo interno, debe pesar Empathic Guide más que Community Builder o Diplomatic Social Connector.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_diplomatic_connector_multi_actor_001",
    title: "Puente entre partes, actores o áreas",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Siempre termino en el medio cuando hay áreas, personas o intereses cruzados. Hablo con uno, con otro, leo qué necesita cada parte y destrabo para que puedan avanzar sin romperse.",
    expectedPrimaryFamily: "diplomatic_social_connector",
    acceptableFamilies: ["diplomatic_social_connector", "institutional_operator"],
    rivalFamilies: ["empathic_guide", "community_builder"],
    keyHumanLanguage: [
      "en el medio",
      "áreas",
      "intereses cruzados",
      "hablo con uno y con otro",
      "cada parte",
      "destrabo",
      "avanzar sin romperse",
    ],
    missingCuesDetected: [
      "intereses cruzados debe pesar como mediación entre partes",
      "destrabar entre áreas debe empujar a diplomatic_social_connector",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando el foco está en varias partes, intereses cruzados y destrabe relacional, debe pesar Diplomatic Social Connector más que Empathic Guide.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_technical_builder_ex_bancario_motores_001",
    title: "Ex bancario con deseo técnico-práctico ligado a motores y autos",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Trabajo en un banco desde hace años, pero estoy harto y quiero salir para hacer algo que me guste. De chico jugaba con autitos de carrera, armaba pistas, desarmaba y armaba cosas. Me gustaba hacer que motores a pila funcionen. En mis ratos libres leo sobre componentes mecánicos y eléctricos de autos de carrera. Me veo más en un taller armando motores que estando en un banco. Tengo conocimiento por cursos técnicos y quiero recibir autos de carrera para incorporar motores adicionales y elementos electrónicos.",
    expectedPrimaryFamily: "technical_builder",
    acceptableFamilies: ["technical_builder", "system_designer"],
    rivalFamilies: [
      "system_designer",
      "analytical_strategist",
      "institutional_operator",
    ],
    keyHumanLanguage: [
      "desarmaba y armaba cosas",
      "hacer que motores funcionen",
      "motores a pila",
      "componentes mecánicos",
      "componentes eléctricos",
      "autos de carrera",
      "taller",
      "armando motores",
      "cursos técnicos",
      "elementos electrónicos",
      "salir del banco",
    ],
    missingCuesDetected: [
      "motores debe pesar como señal técnica-práctica",
      "desarmar y armar cosas debe activar Technical Builder",
      "taller debe empujar más a Technical Builder que a System Designer",
      "componentes mecánicos y eléctricos deben contar como evidencia técnica concreta",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando una persona expresa deseo sostenido de desarmar, armar, reparar, hacer funcionar motores, trabajar con componentes mecánicos/eléctricos y verse en un taller, Technical Builder debe aparecer como hipótesis principal o al menos como hipótesis asistida por aprendizaje, aunque el motor principal no detecte suficiente evidencia.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_creative_storyteller_educator_frontier_001",
    title: "Escritura, relato y explicación clara como frontera vocacional",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText: [
      "Trabajo en una oficina hace años, pero siento que me apago.",
      "Lo que más me sale naturalmente es escribir, explicar ideas, armar textos, contar historias y encontrar una forma clara de decir cosas que otros no logran expresar.",
      "Me gustaba inventar historias, escribir diálogos, hacer revistas caseras y preparar pequeñas actuaciones para mi familia.",
      "Me atraía cómo una frase podía cambiar la forma en que alguien entendía algo.",
      "Siempre termino redactando mensajes, ordenando presentaciones, corrigiendo textos o ayudando a otros a decir mejor lo que quieren decir.",
      "Suelo ser quien pone en palabras lo que está dando vueltas.",
      "Dejé de escribir, de armar contenido y de mostrar ideas propias porque sentía que eso no era serio o no daba plata.",
      "Mi voz propia está comprimida.",
      "Me gustaría dedicarme a comunicar, escribir, hacer contenido o contar historias con sentido.",
    ].join(" "),
    expectedPrimaryFamily: "creative_storyteller",
    acceptableFamilies: ["creative_storyteller", "educator_interpreter"],
    rivalFamilies: ["public_communicator", "cultural_explorer"],
    keyHumanLanguage: [
      "escribir",
      "explicar ideas",
      "armar textos",
      "contar historias",
      "forma clara de decir",
      "inventar historias",
      "escribir diálogos",
      "revistas caseras",
      "frase",
      "entendía algo",
      "redactando mensajes",
      "corrigiendo textos",
      "poner en palabras",
      "voz propia",
      "comunicar",
      "contenido",
      "relatos útiles",
    ],
    missingCuesDetected: [
      "escribir, contar historias y armar textos deben sostener Creative Storyteller",
      "explicar ideas y ayudar a otros a comprender deben abrir frontera con Educator Interpreter",
      "comunicar o contenido no deben activar automáticamente Public Communicator si no hay postura pública, audiencia, agenda o intervención social explícita",
      "voz propia comprimida debe leerse como capacidad expresiva enterrada, no como mera preferencia superficial",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando una persona muestra deseo sostenido de escribir, contar historias, armar textos, encontrar forma verbal y poner en palabras lo que otros no logran expresar, Creative Storyteller debe quedar muy alto. Si además aparece impulso de explicar ideas para que otros comprendan, Educator Interpreter debe aparecer como frontera aceptable. No debe confundirse automáticamente con Public Communicator si no hay audiencia pública, postura, agenda o intervención social explícita.",
    shouldInfluenceFutureCases: true,
  },
];