import type { LearnedDiagnosticCase } from "../types/learning";

export const LEARNED_DIAGNOSTIC_CASES: LearnedDiagnosticCase[] = [
  {
    id: "learned_technical_builder_electric_practical_001",
    title: "Técnico eléctrico práctico que hace funcionar cosas reales",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Me gusta arreglar cosas, encontrar fallas, revisar instalaciones, probar hasta que funcione, cambiar piezas, mirar tableros, meter mano y dejar andando algo que no andaba.",
    expectedPrimaryFamily: "technical_builder",
    acceptableFamilies: ["technical_builder", "system_designer"],
    rivalFamilies: ["system_designer", "analytical_strategist"],
    keyHumanLanguage: [
      "arreglar cosas",
      "encontrar fallas",
      "probar hasta que funcione",
      "meter mano",
      "dejar andando",
      "no andaba",
      "instalaciones",
      "tableros",
    ],
    missingCuesDetected: [
      "dejar andando debe pesar como señal práctica/técnica",
      "meter mano debe empujar más a technical_builder que a system_designer",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando la persona habla de reparar, probar, meter mano y dejar funcionando algo real, el sistema debe mirar primero Technical Builder antes que System Designer.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_system_designer_architecture_001",
    title: "Diseñador de sistemas que piensa estructuras antes que ejecución",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Cuando veo un problema, no me interesa solamente arreglarlo rápido. Me interesa entender cómo está armado el sistema, qué piezas dependen de otras, qué flujo está mal diseñado y cómo evitar que vuelva a romperse.",
    expectedPrimaryFamily: "system_designer",
    acceptableFamilies: ["system_designer", "analytical_strategist"],
    rivalFamilies: ["technical_builder", "analytical_strategist"],
    keyHumanLanguage: [
      "cómo está armado el sistema",
      "piezas dependen de otras",
      "flujo mal diseñado",
      "evitar que vuelva a romperse",
      "diseñar estructura",
    ],
    missingCuesDetected: [
      "evitar que vuelva a romperse debe pesar como señal de diseño sistémico",
      "flujo mal diseñado debe empujar más a system_designer que a technical_builder",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando el foco está en arquitectura, dependencias, flujos y prevención estructural, debe pesar System Designer por encima de Technical Builder.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_creative_storyteller_no_public_front_001",
    title: "Relato y forma narrativa sin deseo de escena pública",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Me gusta escribir, editar, encontrar el tono, darle forma a una idea y volver texto algo que estaba suelto. No sé si quiero estar al frente ni poner la cara; me interesa más la forma que ocupar una voz pública.",
    expectedPrimaryFamily: "creative_storyteller",
    acceptableFamilies: ["creative_storyteller", "public_communicator"],
    rivalFamilies: ["public_communicator", "educator_interpreter"],
    keyHumanLanguage: [
      "escribir",
      "editar",
      "encontrar el tono",
      "darle forma",
      "volver texto",
      "no quiero estar al frente",
      "no poner la cara",
      "me interesa más la forma",
    ],
    missingCuesDetected: [
      "rechazo del frente público debe bajar public_communicator",
      "interés por forma, tono y texto debe sostener creative_storyteller",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando hay escritura, edición, tono y forma narrativa con rechazo explícito del frente público, Creative Storyteller debe quedar por encima o al menos empatado con Public Communicator.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_public_communicator_stance_001",
    title: "Voz pública con postura y necesidad de decir",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Cuando un tema me importa, necesito tomar postura, ordenar lo que está en juego y decirlo claro para otros. No escribo sólo por escribir: me interesa fijar posición y mover una conversación pública.",
    expectedPrimaryFamily: "public_communicator",
    acceptableFamilies: ["public_communicator", "creative_storyteller"],
    rivalFamilies: ["creative_storyteller", "educator_interpreter"],
    keyHumanLanguage: [
      "tomar postura",
      "qué está en juego",
      "decirlo claro para otros",
      "fijar posición",
      "conversación pública",
      "tema me importa",
    ],
    missingCuesDetected: [
      "tomar postura debe empujar a public_communicator",
      "conversación pública debe pesar más que escritura genérica",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando la escritura está al servicio de postura, agenda, tema público o intervención hacia otros, Public Communicator debe superar a Creative Storyteller.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_empathic_guide_one_to_one_001",
    title: "Acompañamiento uno a uno, no coordinación grupal",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "La gente me termina contando cosas. Me sale escuchar, hacer preguntas, ayudar a que alguien ordene lo que le pasa y acompañar sin invadir. No soy tanto de armar grupos ni de mediar entre sectores.",
    expectedPrimaryFamily: "empathic_guide",
    acceptableFamilies: ["empathic_guide"],
    rivalFamilies: ["community_builder", "diplomatic_social_connector"],
    keyHumanLanguage: [
      "me cuentan cosas",
      "escuchar",
      "hacer preguntas",
      "ordenar lo que le pasa",
      "acompañar sin invadir",
      "no soy tanto de armar grupos",
      "no mediar entre sectores",
    ],
    missingCuesDetected: [
      "acompañamiento uno a uno debe pesar más que coordinación grupal",
      "rechazo de armar grupos debe bajar community_builder",
      "rechazo de mediar entre sectores debe bajar diplomatic_social_connector",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando el objeto es una persona individual y su mundo interno, debe pesar Empathic Guide más que Community Builder o Diplomatic Social Connector.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_diplomatic_connector_multi_actor_001",
    title: "Puente entre partes, actores o áreas",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Siempre termino en el medio cuando hay áreas, personas o intereses cruzados. Hablo con uno, con otro, leo qué necesita cada parte y destrabo para que puedan avanzar sin romperse.",
    expectedPrimaryFamily: "diplomatic_social_connector",
    acceptableFamilies: ["diplomatic_social_connector", "institutional_operator"],
    rivalFamilies: ["empathic_guide", "community_builder"],
    keyHumanLanguage: [
      "en el medio",
      "áreas",
      "intereses cruzados",
      "hablo con uno y con otro",
      "cada parte",
      "destrabo",
      "avanzar sin romperse",
    ],
    missingCuesDetected: [
      "intereses cruzados debe pesar como mediación entre partes",
      "destrabar entre áreas debe empujar a diplomatic_social_connector",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando el foco está en varias partes, intereses cruzados y destrabe relacional, debe pesar Diplomatic Social Connector más que Empathic Guide.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_technical_builder_ex_bancario_motores_001",
    title: "Ex bancario con deseo técnico-práctico ligado a motores y autos",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText:
      "Trabajo en un banco desde hace años, pero estoy harto y quiero salir para hacer algo que me guste. De chico jugaba con autitos de carrera, armaba pistas, desarmaba y armaba cosas. Me gustaba hacer que motores a pila funcionen. En mis ratos libres leo sobre componentes mecánicos y eléctricos de autos de carrera. Me veo más en un taller armando motores que estando en un banco. Tengo conocimiento por cursos técnicos y quiero recibir autos de carrera para incorporar motores adicionales y elementos electrónicos.",
    expectedPrimaryFamily: "technical_builder",
    acceptableFamilies: ["technical_builder", "system_designer"],
    rivalFamilies: [
      "system_designer",
      "analytical_strategist",
      "institutional_operator",
    ],
    keyHumanLanguage: [
      "desarmaba y armaba cosas",
      "hacer que motores funcionen",
      "motores a pila",
      "componentes mecánicos",
      "componentes eléctricos",
      "autos de carrera",
      "taller",
      "armando motores",
      "cursos técnicos",
      "elementos electrónicos",
      "salir del banco",
    ],
    missingCuesDetected: [
      "motores debe pesar como señal técnica-práctica",
      "desarmar y armar cosas debe activar Technical Builder",
      "taller debe empujar más a Technical Builder que a System Designer",
      "componentes mecánicos y eléctricos deben contar como evidencia técnica concreta",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando una persona expresa deseo sostenido de desarmar, armar, reparar, hacer funcionar motores, trabajar con componentes mecánicos/eléctricos y verse en un taller, Technical Builder debe aparecer como hipótesis principal o al menos como hipótesis asistida por aprendizaje, aunque el motor principal no detecte suficiente evidencia.",
    shouldInfluenceFutureCases: true,
  },
  {
    id: "learned_creative_storyteller_educator_frontier_001",
    title: "Escritura, relato y explicación clara como frontera vocacional",
    source: "manual_synthetic",
    language: "es",
    region: "Argentina",
    inputText: [
      "Trabajo en una oficina hace años, pero siento que me apago.",
      "Lo que más me sale naturalmente es escribir, explicar ideas, armar textos, contar historias y encontrar una forma clara de decir cosas que otros no logran expresar.",
      "Me gustaba inventar historias, escribir diálogos, hacer revistas caseras y preparar pequeñas actuaciones para mi familia.",
      "Me atraía cómo una frase podía cambiar la forma en que alguien entendía algo.",
      "Siempre termino redactando mensajes, ordenando presentaciones, corrigiendo textos o ayudando a otros a decir mejor lo que quieren decir.",
      "Suelo ser quien pone en palabras lo que está dando vueltas.",
      "Dejé de escribir, de armar contenido y de mostrar ideas propias porque sentía que eso no era serio o no daba plata.",
      "Mi voz propia está comprimida.",
      "Me gustaría dedicarme a comunicar, escribir, hacer contenido o contar historias con sentido.",
    ].join(" "),
    expectedPrimaryFamily: "creative_storyteller",
    acceptableFamilies: ["creative_storyteller", "educator_interpreter"],
    rivalFamilies: ["public_communicator", "cultural_explorer"],
    keyHumanLanguage: [
      "escribir",
      "explicar ideas",
      "armar textos",
      "contar historias",
      "forma clara de decir",
      "inventar historias",
      "escribir diálogos",
      "revistas caseras",
      "frase",
      "entendía algo",
      "redactando mensajes",
      "corrigiendo textos",
      "poner en palabras",
      "voz propia",
      "comunicar",
      "contenido",
      "relatos útiles",
    ],
    missingCuesDetected: [
      "escribir, contar historias y armar textos deben sostener Creative Storyteller",
      "explicar ideas y ayudar a otros a comprender deben abrir frontera con Educator Interpreter",
      "comunicar o contenido no deben activar automáticamente Public Communicator si no hay postura pública, audiencia, agenda o intervención social explícita",
      "voz propia comprimida debe leerse como capacidad expresiva enterrada, no como mera preferencia superficial",
    ],
    verdict: "learning_candidate",
    lesson:
      "Cuando una persona muestra deseo sostenido de escribir, contar historias, armar textos, encontrar forma verbal y poner en palabras lo que otros no logran expresar, Creative Storyteller debe quedar muy alto. Si además aparece impulso de explicar ideas para que otros comprendan, Educator Interpreter debe aparecer como frontera aceptable. No debe confundirse automáticamente con Public Communicator si no hay audiencia pública, postura, agenda o intervención social explícita.",
    shouldInfluenceFutureCases: true,
  },
    {
      id: "learned_public_communicator_public_stance_002",
      title: "Comunicación pública con postura, agenda y audiencia",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Me pasa que cuando veo un tema social o político mal explicado, necesito ordenar qué está pasando, tomar postura y decirlo públicamente. No me alcanza con escribir algo lindo: quiero que el texto sirva para mover una conversación, instalar una idea o discutir una mirada. Me imagino escribiendo columnas, haciendo editoriales, armando hilos, hablando en radio o generando contenido donde haya una posición clara frente a una audiencia.",
      expectedPrimaryFamily: "public_communicator",
      acceptableFamilies: ["public_communicator", "civic_advocate"],
      rivalFamilies: ["creative_storyteller", "educator_interpreter"],
      keyHumanLanguage: [
        "tema social",
        "tema político",
        "tomar postura",
        "decirlo públicamente",
        "mover una conversación",
        "instalar una idea",
        "discutir una mirada",
        "columnas",
        "editoriales",
        "hilos",
        "radio",
        "contenido",
        "posición clara",
        "audiencia",
      ],
      missingCuesDetected: [
        "tomar postura debe pesar más hacia Public Communicator que hacia Creative Storyteller",
        "audiencia explícita debe activar lectura pública",
        "instalar una idea debe contar como señal de agenda pública",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando la escritura aparece al servicio de postura, agenda, intervención pública, audiencia explícita o discusión colectiva, Public Communicator debe pesar por encima de Creative Storyteller. La forma narrativa puede estar presente, pero no debe dominar si el objeto principal es intervenir en conversación pública.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_educator_interpreter_clarity_for_others_002",
      title: "Explicar para que otros comprendan mejor",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Siempre termino explicando cosas. En el trabajo, cuando alguien no entiende un proceso, me sale desarmarlo en partes, buscar ejemplos simples y traducirlo a un lenguaje que la otra persona pueda entender. Me gusta cuando alguien me dice 'ahora sí lo entendí'. No necesito estar al frente de una causa ni tener una voz pública: lo que más me importa es ayudar a que otros comprendan algo que parecía confuso.",
      expectedPrimaryFamily: "educator_interpreter",
      acceptableFamilies: ["educator_interpreter", "empathic_guide"],
      rivalFamilies: ["public_communicator", "creative_storyteller", "analytical_strategist"],
      keyHumanLanguage: [
        "explicando cosas",
        "alguien no entiende",
        "desarmarlo en partes",
        "ejemplos simples",
        "traducirlo",
        "lenguaje que la otra persona pueda entender",
        "ahora sí lo entendí",
        "ayudar a que otros comprendan",
        "confuso",
      ],
      missingCuesDetected: [
        "explicar para comprensión ajena debe pesar más hacia Educator Interpreter",
        "traducir complejidad a lenguaje simple no debe confundirse automáticamente con Public Communicator",
        "no necesitar voz pública debe reducir adjudicación pública",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando el centro del relato es traducir complejidad para que otros comprendan, usando ejemplos, partes, claridad y adaptación al receptor, Educator Interpreter debe pesar por encima de Public Communicator y Creative Storyteller. La clave no es expresarse ni tomar postura, sino producir comprensión en otros.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_creative_storyteller_private_voice_002",
      title: "Voz narrativa propia sin agenda pública",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Desde chico me gustó inventar escenas, escribir diálogos, imaginar personajes y encontrar una forma propia de contar lo que me pasa. A veces escribo textos que no publico, sólo porque necesito darles forma. Me interesa el tono, la atmósfera, la frase justa, la emoción que queda después de leer algo. No pienso tanto en convencer a una audiencia ni en explicar un tema: me interesa construir una voz y transformar experiencias en relato.",
      expectedPrimaryFamily: "creative_storyteller",
      acceptableFamilies: ["creative_storyteller"],
      rivalFamilies: ["public_communicator", "educator_interpreter", "cultural_explorer"],
      keyHumanLanguage: [
        "inventar escenas",
        "escribir diálogos",
        "imaginar personajes",
        "forma propia de contar",
        "textos que no publico",
        "darles forma",
        "tono",
        "atmósfera",
        "frase justa",
        "emoción",
        "construir una voz",
        "transformar experiencias en relato",
      ],
      missingCuesDetected: [
        "textos que no publico debe reducir Public Communicator",
        "tono, atmósfera y frase justa deben pesar hacia Creative Storyteller",
        "transformar experiencia en relato debe activar núcleo narrativo",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando la persona habla de voz propia, escenas, diálogos, tono, atmósfera, frase justa y transformación de experiencia en relato, Creative Storyteller debe pesar con fuerza. Si no hay audiencia, postura, agenda pública ni intención de enseñar, no debe arrastrarse automáticamente hacia Public Communicator o Educator Interpreter.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_public_communicator_educator_frontier_001",
      title: "Comunicación pública que también busca explicar",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Me gusta agarrar temas difíciles de actualidad, ordenarlos y explicarlos para que más gente entienda qué está pasando. Pero no lo haría como una clase neutra: también me importa señalar qué está en juego, marcar una posición y ayudar a que otros puedan mirar el tema de otra manera. Me imagino haciendo videos, columnas o charlas donde combino explicación clara con postura pública.",
      expectedPrimaryFamily: "public_communicator",
      acceptableFamilies: ["public_communicator", "educator_interpreter"],
      rivalFamilies: ["creative_storyteller", "civic_advocate"],
      keyHumanLanguage: [
        "temas difíciles de actualidad",
        "ordenarlos",
        "explicarlos",
        "más gente entienda",
        "qué está pasando",
        "no como una clase neutra",
        "qué está en juego",
        "marcar una posición",
        "mirar el tema de otra manera",
        "videos",
        "columnas",
        "charlas",
        "explicación clara",
        "postura pública",
      ],
      missingCuesDetected: [
        "explicación clara más postura pública debe abrir frontera Public Communicator / Educator Interpreter",
        "actualidad, posición y audiencia deben sostener Public Communicator",
        "comprensión ajena debe sostener Educator Interpreter como familia aceptable",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando una persona combina explicación clara para otros con postura pública, actualidad, audiencia y señalamiento de lo que está en juego, el sistema debe abrir una frontera Public Communicator / Educator Interpreter. Si la postura y la audiencia son explícitas, Public Communicator puede quedar primero, pero Educator Interpreter debe permanecer como familia aceptable fuerte.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_public_communicator_editorial_agenda_001",
      title: "Comunicación pública con agenda, audiencia y postura editorial",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Me pasa que cuando veo un tema social o político importante necesito ordenarlo, tomar postura y escribir algo que otros puedan leer. No me alcanza con entenderlo para mí: quiero convertirlo en una explicación pública, con una mirada clara, una agenda y una voz que pueda circular. Me interesan las columnas, editoriales, hilos, programas o espacios donde una idea pueda influir en una conversación más amplia.",
      expectedPrimaryFamily: "public_communicator",
      acceptableFamilies: ["public_communicator", "educator_interpreter"],
      rivalFamilies: [
        "creative_storyteller",
        "civic_advocate",
        "institutional_operator",
      ],
      keyHumanLanguage: [
        "tema social",
        "tema político",
        "tomar postura",
        "explicación pública",
        "mirada clara",
        "agenda",
        "voz que pueda circular",
        "columnas",
        "editoriales",
        "hilos",
        "programas",
        "conversación más amplia",
      ],
      missingCuesDetected: [
        "tomar postura y agenda deben pesar como señal fuerte de Public Communicator",
        "audiencia o circulación pública deben diferenciar Public Communicator de Creative Storyteller",
        "explicar públicamente puede apoyar Educator Interpreter, pero no debe desplazar Public Communicator si hay postura y audiencia",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando la persona habla de temas sociales o políticos, toma postura, construye agenda, busca audiencia y quiere intervenir en una conversación pública, Public Communicator debe pesar por encima de Creative Storyteller y Educator Interpreter. Educator Interpreter puede quedar como familia aceptable si hay explicación clara para otros.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_educator_interpreter_clear_explanation_no_public_agenda_001",
      title: "Explicación clara para comprensión ajena sin agenda pública",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Me gusta agarrar temas difíciles y hacerlos entendibles. Si alguien no comprende algo, trato de buscar ejemplos, ordenar la idea paso por paso y traducirlo a un lenguaje más simple. No necesariamente quiero opinar en público ni instalar una agenda; lo que más me importa es que la otra persona finalmente entienda.",
      expectedPrimaryFamily: "educator_interpreter",
      acceptableFamilies: ["educator_interpreter"],
      rivalFamilies: [
        "public_communicator",
        "creative_storyteller",
        "analytical_strategist",
      ],
      keyHumanLanguage: [
        "temas difíciles",
        "hacerlos entendibles",
        "buscar ejemplos",
        "ordenar la idea paso por paso",
        "traducirlo a un lenguaje más simple",
        "no quiero opinar en público",
        "no instalar una agenda",
        "que la otra persona entienda",
      ],
      missingCuesDetected: [
        "explicar para que otro comprenda debe activar Educator Interpreter",
        "no querer opinar en público debe limitar Public Communicator",
        "ordenar paso a paso no debe convertirse automáticamente en Analytical Strategist si el destino es comprensión ajena",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando el foco principal es traducir complejidad para que otra persona comprenda, sin agenda pública, postura ni audiencia amplia, Educator Interpreter debe quedar por encima de Public Communicator y Creative Storyteller.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_civic_advocate_cause_pressure_001",
      title: "Incidencia cívica con causa, presión y cambio concreto",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Cuando veo una injusticia o un problema colectivo, me cuesta quedarme quieto. Pienso en cómo denunciarlo, juntar gente, presionar a quienes tienen responsabilidad y lograr que algo cambie. Puedo escribir o hablar en público, pero no es sólo comunicar: me interesa empujar una causa, incomodar si hace falta y conseguir una respuesta concreta.",
      expectedPrimaryFamily: "civic_advocate",
      acceptableFamilies: ["civic_advocate", "public_communicator"],
      rivalFamilies: [
        "public_communicator",
        "diplomatic_social_connector",
        "institutional_operator",
      ],
      keyHumanLanguage: [
        "injusticia",
        "problema colectivo",
        "denunciarlo",
        "juntar gente",
        "presionar",
        "responsabilidad",
        "lograr que algo cambie",
        "empujar una causa",
        "incomodar",
        "respuesta concreta",
      ],
      missingCuesDetected: [
        "injusticia, causa y presión deben activar Civic Advocate",
        "hablar o escribir en público no alcanza para Public Communicator si el centro es incidencia y cambio",
        "presionar responsables no debe confundirse con Diplomatic Social Connector si no hay mediación sino exigencia",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando la comunicación está al servicio de una causa, denuncia, presión pública o cambio colectivo concreto, Civic Advocate debe pesar más que Public Communicator. Public Communicator puede quedar como familia aceptable si hay voz pública fuerte.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_institutional_operator_formal_navigation_001",
      title: "Operador institucional que entiende reglas, áreas y procedimientos",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "En los trabajos donde mejor me muevo es cuando hay reglas, expedientes, áreas, jerarquías y procedimientos. Suelo entender rápido quién decide qué, qué paso falta, qué norma hay que mirar y cómo hacer avanzar algo dentro de una estructura formal. No busco necesariamente hablarle al público ni levantar una causa; me interesa que el trámite, el circuito o la institución funcionen.",
      expectedPrimaryFamily: "institutional_operator",
      acceptableFamilies: ["institutional_operator", "diplomatic_social_connector"],
      rivalFamilies: [
        "public_communicator",
        "civic_advocate",
        "analytical_strategist",
      ],
      keyHumanLanguage: [
        "reglas",
        "expedientes",
        "áreas",
        "jerarquías",
        "procedimientos",
        "quién decide qué",
        "qué paso falta",
        "qué norma",
        "estructura formal",
        "trámite",
        "circuito",
        "institución",
      ],
      missingCuesDetected: [
        "reglas, expedientes, jerarquías y procedimientos deben activar Institutional Operator",
        "institución no debe empujar automáticamente a Civic Advocate si no hay causa o presión pública",
        "áreas y estructura formal pueden apoyar Diplomatic Social Connector sólo si hay articulación entre partes",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando la persona se orienta por reglas, procedimientos, jerarquías, expedientes, circuitos y funcionamiento interno de una estructura formal, Institutional Operator debe pesar por encima de Public Communicator o Civic Advocate, salvo que aparezcan audiencia pública, causa o presión social explícita.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_diplomatic_social_connector_between_actors_001",
      title: "Conector diplomático entre actores con intereses distintos",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Muchas veces termino siendo quien habla con una parte y con la otra. Me doy cuenta de qué necesita cada actor, qué le molesta a cada lado y dónde se puede destrabar la conversación. No me interesa tanto denunciar ni tomar postura pública; prefiero encontrar un punto de acuerdo para que las partes puedan avanzar sin romper la relación.",
      expectedPrimaryFamily: "diplomatic_social_connector",
      acceptableFamilies: [
        "diplomatic_social_connector",
        "institutional_operator",
      ],
      rivalFamilies: [
        "civic_advocate",
        "public_communicator",
        "empathic_guide",
      ],
      keyHumanLanguage: [
        "una parte y la otra",
        "cada actor",
        "cada lado",
        "destrabar la conversación",
        "no denunciar",
        "no tomar postura pública",
        "punto de acuerdo",
        "las partes",
        "avanzar sin romper la relación",
      ],
      missingCuesDetected: [
        "partes, actores, lados y acuerdo deben activar Diplomatic Social Connector",
        "no denunciar y no tomar postura pública deben limitar Civic Advocate y Public Communicator",
        "acompañar vínculos entre partes no debe confundirse con Empathic Guide si el objeto no es una persona individual sino una relación entre actores",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando el foco está en leer actores, destrabar conversaciones, cuidar relaciones y encontrar acuerdos entre partes distintas, Diplomatic Social Connector debe pesar por encima de Civic Advocate, Public Communicator y Empathic Guide.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_public_communicator_vs_institutional_boundary_001",
      title: "Comunicación sobre instituciones sin operación institucional directa",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Me interesa explicar cómo funcionan las instituciones, qué decisiones se toman, qué intereses aparecen y cómo eso afecta a la gente. Pero no me imagino haciendo expedientes ni llevando circuitos internos. Me veo más escribiendo, hablando o armando análisis para una audiencia que necesita entender lo que pasa dentro del poder.",
      expectedPrimaryFamily: "public_communicator",
      acceptableFamilies: [
        "public_communicator",
        "educator_interpreter",
        "institutional_operator",
      ],
      rivalFamilies: [
        "institutional_operator",
        "civic_advocate",
        "analytical_strategist",
      ],
      keyHumanLanguage: [
        "explicar cómo funcionan las instituciones",
        "decisiones",
        "intereses",
        "afecta a la gente",
        "no expedientes",
        "no circuitos internos",
        "escribiendo",
        "hablando",
        "análisis para una audiencia",
        "entender lo que pasa dentro del poder",
      ],
      missingCuesDetected: [
        "hablar sobre instituciones no debe activar automáticamente Institutional Operator",
        "si el destino es audiencia y explicación pública, Public Communicator debe pesar más que Institutional Operator",
        "Educator Interpreter puede quedar como apoyo si el foco es hacer comprensible la complejidad institucional",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando la persona interpreta instituciones para una audiencia, sin interés en operar expedientes, normas o circuitos internos, Public Communicator debe pesar por encima de Institutional Operator. Institutional Operator puede quedar como familia aceptable sólo por contenido institucional, no como dirección principal.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_empathic_guide_institutional_frontier_001",
      title: "Guía empática con frontera institucional",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "En distintos momentos termino siendo la persona a la que alguien busca cuando está confundido, triste o no sabe cómo poner en palabras lo que le pasa. Me sale escuchar sin apurar, hacer una pregunta justa y ayudar a que la otra persona entienda qué siente y qué necesita. No me interesa dirigir grupos ni organizar equipos; me interesa acompañar procesos personales. Muchas veces sostengo emocionalmente a otros y después me cuesta encontrar un lugar donde esa capacidad tenga forma real, sin quedar como favor invisible. Quiero que esto deje de ser solo ayuda informal y encontrar un marco laboral más claro para esta capacidad.",
      expectedPrimaryFamily: "empathic_guide",
      acceptableFamilies: ["empathic_guide", "institutional_operator"],
      rivalFamilies: ["community_builder", "diplomatic_social_connector"],
      keyHumanLanguage: [
        "la persona a la que alguien busca",
        "confundido",
        "triste",
        "poner en palabras lo que le pasa",
        "escuchar sin apurar",
        "pregunta justa",
        "entienda qué siente",
        "qué necesita",
        "acompañar procesos personales",
        "sostengo emocionalmente a otros",
        "marco laboral más claro",
      ],
      missingCuesDetected: [
        "escucha profunda y clarificación uno a uno deben sostener Empathic Guide",
        "buscar formalización o marco laboral no debe subir Institutional Operator por sí solo",
        "sin coordinación grupal ni pertenencia colectiva no debe subir Community Builder",
        "sin mediación entre actores, partes o intereses en conflicto no debe subir Diplomatic Social Connector",
      ],
      verdict: "learning_candidate",
      lesson:
        "Este caso enseña que una persona puede mostrar una dirección principal de Guía Empática cuando el foco está en escucha profunda, comprensión emocional, clarificación humana uno a uno y acompañamiento de procesos personales. La búsqueda de un marco laboral más claro o cierto lenguaje de organización/institución puede abrir frontera con Institutional Operator, pero no debe desplazar a Empathic Guide si no hay señales dominantes de operación formal, reglas, expedientes, jerarquías o procedimientos institucionales.",
      shouldInfluenceFutureCases: true,
    },
    // QUARANTINE: language contains metadata/lab contamination; do not promote until rewritten in natural human language.
    {
      id: "learned_system_designer_institutional_edge_001",
      title: "Diseñador de sistemas con borde institucional",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Lidera mejora de procesos entre áreas con herramientas nuevas y resistencia cultural fuerte. Repite que diseña flujos, define criterios, alinea herramientas y roles para que la organización no dependa de héroes. Siente cansancio por parches eternos sin rediseño y procesos incoherentes. Sus restricciones son legado tecnológico feo y política interna de silos. Sus activos son visión de flujo end-to-end, documentación clara y facilitación de acuerdos. Desde chica armaba reglas para juegos porque si no era un caos; le importaba que el sistema cierre. Le interesa cómo encajan piezas que parecen independientes hasta que se ve el mapa entero. Quiere instalar governance liviana que dure, no solo workshops con post-its. Se reconoce no solo como quien ejecuta tareas, sino como quien piensa cómo debería funcionar el conjunto.",
      expectedPrimaryFamily: "system_designer",
      acceptableFamilies: ["system_designer"],
      rivalFamilies: [
        "institutional_operator",
        "technical_builder",
        "analytical_strategist",
        "diplomatic_social_connector",
      ],
      keyHumanLanguage: [
        "diseño flujos",
        "defino criterios",
        "alineo herramientas y roles",
        "que la organización no dependa de héroes",
        "instalar governance liviana",
        "que dure",
        "no solo workshops",
        "visión de flujo end-to-end",
        "documentación clara",
        "el que mira el sistema",
        "cómo debería funcionar el conjunto",
        "procesos incoherentes",
        "el sistema cierre",
      ],
      missingCuesDetected: [
        "metadata_contamination_review_required: inputText is third-person lab/catalog voice, not first-person intake",
        "quarantine_language_contaminated",
        "mencionar áreas, roles, governance u organización no debe convertir automáticamente el caso en Institutional Operator",
        "si el foco está en diseñar el mecanismo, las reglas, los flujos y la arquitectura del proceso, debe sostener System Designer",
        "Technical Builder solo debería subir si el centro es construir técnicamente la herramienta, no diseñar el sistema de funcionamiento",
        "Analytical Strategist solo debería subir si el centro es lectura estratégica/decisional más que diseño operativo del sistema",
      ],
      actualResult: {
        corePattern: "system_designer / institutional_operator (institutional edge leve)",
        resultType: "clear_direction",
        familyScores: [
          {
            topFamily: "system_designer",
            secondFamily: "institutional_operator",
            topConfidence: 0.81,
            secondConfidence: 0.74,
            note: "System Designer ganó correctamente, con borde institucional leve.",
          },
        ],
      },
      verdict: "learning_candidate",
      lesson:
        "Este caso enseña que una persona puede mostrar lenguaje institucional, de áreas, roles, governance o coordinación organizacional, pero seguir siendo principalmente System Designer cuando el núcleo de evidencia es diseñar flujos, reglas, criterios, arquitectura de proceso y mecanismos para que el sistema funcione sin depender de héroes. Institutional Operator debe quedar como rival/adyacente cuando la persona se mueve dentro de estructuras, pero no desplazar a System Designer si la acción central es rediseñar el funcionamiento.",
      shouldInfluenceFutureCases: false,
    },
    {
      id: "learned_system_designer_public_communicator_frontier_001",
      title: "System Designer con frontera Public Communicator tras R2 manual",
      source: "manual_synthetic",
      language: "es",
      region: "Uruguay",
      inputText:
        "Equipo de producto con deuda de procesos; me piden diseño y al mismo tiempo entrega inmediata. Empiezo mapeando el proceso y termino codeando integraciones porque el plazo aprieta. Si solo me evalúan por tickets cerrados, mi rol de sistema no existe en el papel. La clave no es que yo quiera implementar más rápido ni resolver tickets sueltos. Lo que más me importa es diseñar primero el flujo, las reglas, las responsabilidades y las dependencias del sistema para que después la implementación tenga sentido. Puedo programar o automatizar cuando hace falta, pero mi aporte distintivo aparece antes: ordenar la arquitectura del proceso y evitar que todo dependa de parches.",
      expectedPrimaryFamily: "system_designer",
      acceptableFamilies: ["system_designer", "public_communicator"],
      rivalFamilies: [
        "technical_builder",
        "analytical_strategist",
        "institutional_operator",
      ],
      keyHumanLanguage: [
        "deuda de procesos",
        "me piden diseño y entrega inmediata",
        "mapear el proceso",
        "termino codeando integraciones porque el plazo aprieta",
        "si solo me evalúan por tickets cerrados, mi rol de sistema no existe en el papel",
        "no quiero implementar más rápido ni resolver tickets sueltos",
        "diseñar primero el flujo, las reglas, las responsabilidades y las dependencias",
        "ordenar la arquitectura del proceso",
        "evitar que todo dependa de parches",
        "ordenar el sistema antes que picar código o tareas sueltas",
      ],
      missingCuesDetected: [
        "No confundir capacidad de implementación con Technical Builder cuando la intención dominante es diseñar sistema, flujo, reglas y dependencias.",
        "Si aparece lenguaje de audiencia, voz, mensaje o explicación pública, revisar Public Communicator como frontera, no necesariamente como dominancia.",
        "Si la persona insiste en ordenar arquitectura antes de código o tareas sueltas, favorecer System Designer sobre Technical Builder.",
        "Cuando la salida enriquecida pasa de insufficient_evidence a clear_direction pero aparece una segunda familia muy cercana, conservar el caso como frontera consultable.",
      ],
      actualResult: {
        corePattern: "system_designer / public_communicator frontier",
        resultType: "clear_direction",
        familyScores: [
          {
            originalResultType: "insufficient_evidence",
            enrichedResultType: "clear_direction",
            topFamily: "system_designer",
            frontierFamily: "public_communicator",
            promotionSignal: "frontier_support",
            manualFollowupRound: 2,
          },
        ],
      },
      verdict: "learning_candidate",
      lesson:
        "Este caso enseña que una persona puede parecer Technical Builder porque implementa o codea bajo presión, pero su patrón dominante puede ser System Designer si su preocupación central es diseñar flujo, reglas, responsabilidades, dependencias y arquitectura antes de ejecutar. También muestra que, cuando aparece necesidad de explicar, ordenar agenda o construir mensaje para otros, Public Communicator debe quedar como frontera activa y no como descarte automático.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_public_communicator_educator_interpreter_frontier_001",
      title: "Public Communicator con frontera Educator Interpreter",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "De chico me gustaba explicar a mis amigos por qué una regla del colegio o del club no tenía sentido; terminaba armando ejemplos para que todos entendieran el problema. Me enganchaba ver cómo una idea complicada podía volverse clara si encontraba la frase, el ejemplo y el orden justo. En distintos trabajos termino traduciendo decisiones confusas de equipos técnicos o directivos a mensajes que la gente entienda y pueda discutir. No busco diseñar procesos internos como objetivo principal; quiero construir una voz pública y una explicación clara para una audiencia real. Quiero probar una línea de comunicación pública o institucional donde convierta complejidad en mensajes claros para una audiencia real.",
      expectedPrimaryFamily: "public_communicator",
      acceptableFamilies: ["public_communicator", "educator_interpreter"],
      rivalFamilies: [
        "creative_storyteller",
        "system_designer",
        "institutional_operator",
      ],
      keyHumanLanguage: [
        "traduciendo decisiones confusas",
        "mensajes que la gente entienda",
        "explicar una idea complicada",
        "frase, ejemplo y orden justo",
        "comunicación pública o institucional",
        "audiencia real",
      ],
      missingCuesDetected: [
        "cuando el eje es traducir complejidad para una audiencia, priorizar Public Communicator",
        "si aparece impulso pedagógico de explicación clara, sostener Educator Interpreter como frontera natural",
        "no subir System Designer por defecto solo por lenguaje de estructura si el objeto dominante es voz pública y audiencia",
        "no subir Institutional Operator si no hay operación formal, circuitos internos o foco en trámite institucional",
      ],
      verdict: "learning_candidate",
      lesson:
        "Cuando el eje dominante es convertir complejidad en mensajes claros para una audiencia, y además aparece impulso de enseñanza/explicación, la frontera natural puede ser Public Communicator ↔ Educator Interpreter. No debe forzarse System Designer como frontera principal si la estructura aparece como soporte y no como objeto de diseño central.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_public_communicator_institutional_operator_frontier_001",
      title: "Public Communicator con frontera Institutional Operator",
      source: "manual_synthetic",
      language: "es",
      region: "LatAm",
      inputText:
        "Trabajo creando comunicación pública para temas complejos. Necesito construir agenda, sostener una voz reconocible y ordenar mensajes en el tiempo para que no sean piezas sueltas. Cuando aparecen estructuras formales, reglas de funcionamiento y asuntos colectivos, también debo traducir ese marco a una narrativa clara para audiencia real, sin perder continuidad editorial.",
      expectedPrimaryFamily: "public_communicator",
      acceptableFamilies: ["public_communicator", "institutional_operator"],
      rivalFamilies: [
        "system_designer",
        "educator_interpreter",
        "civic_advocate",
        "creative_storyteller",
      ],
      keyHumanLanguage: [
        "comunicación pública",
        "agenda",
        "voz reconocible",
        "mensajes en el tiempo",
        "estructura formal",
        "reglas de funcionamiento",
        "asuntos colectivos",
        "narrativa clara para audiencia real",
        "continuidad editorial",
      ],
      missingCuesDetected: [
        "agenda y voz pública deben sostener Public Communicator como familia primaria",
        "marco formal y reglas de funcionamiento pueden abrir frontera Institutional Operator",
        "no subir System Designer si la arquitectura aparece como soporte y no como núcleo dominante",
      ],
      verdict: "learning_candidate",
      lesson:
        "Este caso enseña que cuando la comunicación pública aparece junto a agenda, asuntos colectivos, marco institucional o reglas de funcionamiento público, la frontera secundaria puede ser Institutional Operator. No debe confundirse con System Designer salvo que el diseño de arquitectura, dependencias, módulos o flujos sea el núcleo dominante y no solo soporte de la voz pública.",
      shouldInfluenceFutureCases: true,
    },
    // QUARANTINE: language contains metadata/lab contamination; do not promote until rewritten in natural human language.
    {
      id: "learned_empathic_guide_community_builder_frontier_inverted_order_001",
      title:
        "Frontera EG/CB con orden invertido (watchlist)",
      source: "manual_synthetic",
      language: "es",
      region: "LatAm",
      inputText:
        "Caso semilla de guía empática con vocabulario de grupo y clima donde el sistema devolvió #1 Community Builder y #2 Empathic Guide. Ambas familias son plausibles, pero el orden quedó invertido respecto de la expectativa principal de acompañamiento uno a uno profundo.",
      expectedPrimaryFamily: "empathic_guide",
      acceptableFamilies: ["empathic_guide", "community_builder"],
      rivalFamilies: ["diplomatic_social_connector"],
      keyHumanLanguage: [
        "me confunden escuchar profundo con sostener comunidad",
        "a veces hablo de equipo",
        "lo que más me llena es la conversación seria con alguien concreto",
        "me agota llevar el clima",
      ],
      missingCuesDetected: [
        "quarantine_language_contaminated: inputText mixes lab ranking labels with narrative",
        "metadata_contamination_review_required",
        "risk: group_language_overactivates_community_builder",
        "marker: one_to_one_deep_listening_should_weight_empathic_guide",
        "marker: negative contrast against group maintenance should reduce community certainty",
        "warning: no usar palabras como equipo, grupo o clima de forma automática para cerrar Community Builder si el usuario explícitamente diferencia grupo vs acompañamiento individual",
        "use: watchlist",
        "use: frontier_order_case",
        "use: seed_refinement",
      ],
      actualResult: {
        corePattern: "community_builder / empathic_guide (frontier order inverted)",
        resultType: "clear_direction",
        familyScores: [
          {
            expectedPrimaryFamily: "empathic_guide",
            acceptableFamilies: ["empathic_guide", "community_builder"],
            observedTop1: "community_builder",
            observedTop2: "empathic_guide",
            note: "Orden invertido dentro de frontera legítima; caso reservado para calibración fina.",
          },
        ],
      },
      verdict: "borderline",
      lesson:
        "Preservar como caso de frontera auditado: no usar como learned fuerte pro Community Builder. Útil para refinar lectura de contraste explícito entre sostén de grupo y acompañamiento individual profundo.",
      shouldInfluenceFutureCases: false,
    },
    {
      id: "learned_empathic_guide_frontier_refinement_seed_001",
      title:
        "Seed refinado EG>CB con contraste explícito",
      source: "manual_synthetic",
      language: "es",
      region: "LatAm",
      inputText:
        "Me confunden escuchar profundo con sostener comunidad. Uso lenguaje de equipo, pero mi valor real aparece cuando acompaño a una persona concreta a ordenar lo que le pasa. No quiero ser quien mantiene vivo el grupo; quiero ayudar a que alguien entienda su tensión interna. Me agota que me usen para llevar el clima. Lo que más me llena es la conversación seria, no la dinámica grupal.",
      expectedPrimaryFamily: "empathic_guide",
      acceptableFamilies: ["empathic_guide", "community_builder"],
      rivalFamilies: ["diplomatic_social_connector"],
      keyHumanLanguage: [
        "acompaño a una persona concreta",
        "tensión interna",
        "me confunden escuchar profundo con sostener comunidad",
        "no quiero mantener vivo el grupo",
      ],
      missingCuesDetected: [
        "risk: group_language_overactivates_community_builder",
        "marker: one_to_one_deep_listening_should_weight_empathic_guide",
        "marker: negative contrast against group maintenance should reduce community certainty",
      ],
      verdict: "learning_candidate",
      lesson:
        "Seed de refinamiento quirúrgico para validar que Empathic Guide gane cuando el propio relato subordina lo grupal y explicita prioridad uno a uno.",
      shouldInfluenceFutureCases: false,
    },
    {
      id: "learned_community_builder_frontier_refinement_seed_001",
      title:
        "Seed refinado CB>EG con escucha instrumental",
      source: "manual_synthetic",
      language: "es",
      region: "LatAm",
      inputText:
        "Escucho personas una por una para que el grupo no se rompa. Mi valor aparece cuando una comunidad recupera circulación, pertenencia y continuidad. Me interesa diseñar espacios donde la gente vuelva, participe y se sienta parte. La conversación individual es una herramienta para sostener el tejido colectivo.",
      expectedPrimaryFamily: "community_builder",
      acceptableFamilies: ["community_builder", "empathic_guide"],
      rivalFamilies: ["diplomatic_social_connector"],
      keyHumanLanguage: [
        "para que el grupo no se rompa",
        "circulación, pertenencia y continuidad",
        "diseñar espacios",
        "tejido colectivo",
      ],
      missingCuesDetected: [
        "risk: group_language_overactivates_community_builder",
        "marker: one_to_one_deep_listening_should_weight_empathic_guide",
        "marker: negative contrast against group maintenance should reduce community certainty",
        "warning: no usar palabras como equipo, grupo o clima de forma automática para cerrar Community Builder si el usuario explícitamente diferencia grupo vs acompañamiento individual",
      ],
      verdict: "learning_candidate",
      lesson:
        "Seed contrastivo para verificar frontera en sentido opuesto: la escucha individual cuenta como soporte, pero el objeto dominante es sostener comunidad.",
      shouldInfluenceFutureCases: false,
    },
    // QUARANTINE: language contains metadata/lab contamination; do not promote until rewritten in natural human language.
    {
      id: "learned_institutional_operator_diplomatic_connector_language_contamination_warning_001",
      title:
        "institutional_operator_diplomatic_connector_language_contamination_warning",
      source: "manual_synthetic",
      language: "es",
      region: "LatAm",
      inputText:
        "Cuando un relato usa reuniones, acuerdos, actores, mesas, negociación o alinear intereses, el sistema puede sesgar hacia un perfil centrado en mediación entre personas. Para reconocer un operador institucional fuerte, buscar evidencia de conversión formal: expediente, norma aplicable, requisitos, plazos, documentación, auditoría, trazabilidad, circuito cumplible, procedimiento, responsables, cumplimiento y riesgo institucional. Si el valor aparece después de la reunión, bajando lo acordado a estructura formal, debe subir el operador institucional. Si el centro es mediar posiciones, cuidar vínculos o sostener acuerdos entre partes, debe subir la mediación entre actores.",
      expectedPrimaryFamily: "institutional_operator",
      acceptableFamilies: [
        "institutional_operator",
        "diplomatic_social_connector",
      ],
      rivalFamilies: [
        "diplomatic_social_connector",
        "commercial_connector",
        "civic_advocate",
      ],
      keyHumanLanguage: [
        "expediente",
        "norma aplicable",
        "requisitos",
        "plazos",
        "trazabilidad",
        "circuito cumplible",
        "procedimiento",
        "auditoría",
        "reuniones",
        "mesas",
        "acuerdos",
      ],
      missingCuesDetected: [
        "quarantine_language_contaminated: inputText is calibration prose, not simulated user voice",
        "metadata_contamination_review_required",
        "marker: institutional_operator_diplomatic_connector_language_contamination_warning",
        "learningTier: calibration_warning",
        "reviewStatus: frontier_support",
        "humanReviewSuggested: true",
        "influenceWeight: 0",
        "nota: no promover como learned fuerte; calibración y consulta",
      ],
      verdict: "borderline",
      lesson:
        "Advertencia de calibración: lenguaje de reuniones, acuerdos, actores o mesas puede sobreactivar un perfil de mediación. Contrastar con señales de operación formal (expediente, norma, plazos, trazabilidad, riesgo institucional). Si lo valioso es bajar lo acordado a papeles y circuito, priorizar operador institucional; si lo valioso es sostener relación y acuerdo entre partes, priorizar mediación.",
      shouldInfluenceFutureCases: false,
    },
    {
      id: "learned_voc_t1_empathic_guide_one_to_one_001",
      title: "Voc T1 — Escucha humana uno a uno",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText: [
        "Trabajo dentro de una organización, pero donde más rindo es escuchando a fondo a personas sobrepasadas, ordenando conversaciones difíciles y ayudando a entender conflictos humanos sin invadir.",
        "De chico era a quien le contaban cosas difíciles porque podía escuchar a fondo sin apurar ni juzgar.",
        "Me interesaba entender qué le pasaba de verdad a la gente y hacer preguntas que ayudaran a ordenar lo confuso.",
        "Siempre termino escuchando a fondo, conteniendo, haciendo preguntas justas y ayudando a otros a entender situaciones personales complejas.",
        "Mi rol natural es de acompañante, escucha profunda y presencia humana con criterio.",
        "Fui dejando ese costado en segundo plano por tareas más funcionales y menos humanas.",
        "Sostengo mucho a otros, pero eso todavía no está canalizado en una dirección propia clara.",
        "Puedo trabajar con equipos, pero mi aporte real no es sostener comunidad sino acompañar personas una por una con escucha y claridad.",
      ].join(" "),
      expectedPrimaryFamily: "empathic_guide",
      acceptableFamilies: [
        "empathic_guide",
        "community_builder",
        "institutional_operator",
      ],
      rivalFamilies: ["diplomatic_social_connector", "community_builder"],
      keyHumanLanguage: [
        "escuchando a fondo",
        "personas sobrepasadas",
        "ordenando conversaciones difíciles",
        "sin invadir",
        "escuchar sin apurar ni juzgar",
        "preguntas que ayudaran a ordenar",
        "situaciones personales complejas",
        "acompañar personas una por una",
      ],
      missingCuesDetected: [
        "quality: strong_clear_case",
        "learningTier: validated_clear",
        "influenceWeight: high",
        "secondaryFamily: community_builder",
        "tertiaryFamily: institutional_operator",
        "riesgo de confusión con articulación diplomática o sostén comunitario si aparece contexto organizacional",
      ],
      verdict: "learning_candidate",
      lesson:
        "Caso claro de guía empática uno a uno. La presencia de contexto organizacional no debe arrastrar automáticamente hacia operación institucional ni articulación diplomática cuando el centro repetido es acompañar procesos humanos individuales.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_voc_t2_diplomatic_commercial_frontier_001",
      title: "Voc T2 — Articulador de actores, no terapéutico",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText: [
        "Estoy estable, pero donde mejor rindo es coordinando actores, leyendo intereses, conectando sectores y ordenando cruces para destrabar situaciones.",
        "Desde chico tendía a ordenar grupos, leer climas y acercar posiciones entre personas que pensaban distinto.",
        "Me atraían los espacios donde había que interpretar intereses, construir acuerdos y destrabar conflictos entre actores.",
        "Siempre termino articulando personas, mediando tensiones, negociando posiciones y haciendo que distintas partes puedan convivir en un mismo esquema.",
        "Mi rol natural es el de articulador, mediador y lector de actores.",
        "Postergué un desarrollo más expansivo por necesidad de sostener estructura e ingresos.",
        "Siento que esa capacidad está usada de forma defensiva y táctica, no como una función expansiva y bien ubicada.",
        "Tengo sensibilidad interpersonal, pero mi fuerza principal aparece en la lectura de actores y la coordinación política, no en la contención emocional.",
      ].join(" "),
      expectedPrimaryFamily: "diplomatic_social_connector",
      acceptableFamilies: [
        "diplomatic_social_connector",
        "commercial_connector",
        "civic_advocate",
      ],
      rivalFamilies: ["empathic_guide", "community_builder"],
      keyHumanLanguage: [
        "coordinando actores",
        "leyendo intereses",
        "conectando sectores",
        "acercar posiciones",
        "construir acuerdos",
        "mediando tensiones",
        "negociando posiciones",
        "coordinación política",
      ],
      missingCuesDetected: [
        "quality: useful_frontier_case",
        "learningTier: validated_frontier",
        "reviewStatus: frontier_support",
        "influenceWeight: medium",
        "secondaryFamily: commercial_connector",
        "tertiaryFamily: civic_advocate",
        "la empatía interpersonal no debe desplazar lectura de actores y negociación entre partes",
      ],
      verdict: "learning_candidate",
      lesson:
        "Frontera útil entre articulación diplomática y conexión comercial. Cuando la función central es leer actores, negociar posiciones y coordinar partes, no debe confundirse con guía empática.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_voc_t3_community_builder_clear_001",
      title: "Voc T3 — Tejedor de comunidad, no conector institucional",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText: [
        "Hoy donde mejor rindo es sosteniendo comunidad, coordinando grupos, escuchando a la gente y ordenando la circulación entre personas.",
        "De chico armaba clubes, grupos y espacios de pertenencia; me gustaba que la gente se sintiera parte.",
        "Me interesaban las comunidades, los grupos, la circulación entre personas y cómo sostener interacción.",
        "Siempre termino sosteniendo comunidad, coordinando grupos, escuchando a la gente y construyendo mensajes claros para ordenar la interacción.",
        "Mi rol natural es organizar grupos, cuidar el clima y articular pertenencia.",
        "Dejé en segundo plano mi propia dirección por quedarme sosteniendo espacios colectivos.",
        "Mi capacidad de pertenencia y circulación existe, pero hoy aparece más como sostén invisible que como función clara.",
        "Me sale nombrar lo que pasa, cuidar el clima, sostener comunidad y construir relato compartido para que la interacción no se rompa.",
      ].join(" "),
      expectedPrimaryFamily: "community_builder",
      acceptableFamilies: ["community_builder", "creative_storyteller"],
      rivalFamilies: [
        "diplomatic_social_connector",
        "creative_storyteller",
        "empathic_guide",
      ],
      keyHumanLanguage: [
        "sosteniendo comunidad",
        "coordinando grupos",
        "espacios de pertenencia",
        "circulación entre personas",
        "cuidar el clima",
        "articular pertenencia",
        "espacios colectivos",
        "relato compartido",
      ],
      missingCuesDetected: [
        "quality: strong_clear_case",
        "learningTier: validated_clear",
        "influenceWeight: high",
        "secondaryFamily: creative_storyteller",
        "la señal central es pertenencia e interacción colectiva, no mediación entre actores ni acompañamiento individual",
      ],
      verdict: "learning_candidate",
      lesson:
        "Caso claro de constructor de comunidad: debe pesar la pertenencia grupal, la circulación colectiva y el sostén del clima por encima de la diplomacia entre partes o la escucha uno a uno.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_voc_t4_analytical_strategist_system_designer_frontier_001",
      title: "Voc T4 — Analista de criterio, no ejecutor",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText: [
        "Trabajo bien con equipos y clientes, pero donde más rindo es comparando escenarios, leyendo estructura, detectando criterio y viendo oportunidades.",
        "De chico me entretenía comparando caminos posibles y viendo cuál tenía más lógica antes de mover una pieza.",
        "Me interesaban los modelos, la estrategia, los escenarios y cómo funciona un sistema por dentro.",
        "Siempre termino comparando escenarios, ordenando criterios, leyendo estructura, evaluando alternativas y detectando oportunidades.",
        "Mi rol natural es analista, comparador y diseñador de decisiones.",
        "Muchas veces usé esa capacidad solo para responder urgencias en vez de ponerla al centro de mi trabajo.",
        "Mi parte más fuerte aparece pensando escenarios y decisiones, pero hoy queda parcialmente tapada.",
        "Mi diferencial real no es ejecutar rápido sino ver el modelo, la lógica detrás del negocio y el costo de cada camino.",
      ].join(" "),
      expectedPrimaryFamily: "analytical_strategist",
      acceptableFamilies: [
        "analytical_strategist",
        "system_designer",
        "creative_storyteller",
      ],
      rivalFamilies: ["technical_builder"],
      keyHumanLanguage: [
        "comparando escenarios",
        "leyendo estructura",
        "detectando criterio",
        "modelos",
        "estrategia",
        "evaluando alternativas",
        "diseñador de decisiones",
        "lógica detrás del negocio",
      ],
      missingCuesDetected: [
        "quality: useful_frontier_case",
        "learningTier: validated_frontier",
        "reviewStatus: frontier_support",
        "influenceWeight: medium",
        "secondaryFamily: system_designer",
        "tertiaryFamily: creative_storyteller",
        "no confundir lenguaje de procesos o lógica con constructor técnico cuando el centro es criterio y decisión",
        "descartar technical_builder si no hay ejecución concreta dominante",
      ],
      verdict: "learning_candidate",
      lesson:
        "Frontera comparativa entre estratega analítico y diseñador de sistemas. Debe pesar más la lectura de modelo, escenarios y decisiones que la ejecución operativa.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_voc_t5_technical_builder_operational_solver_001",
      title: "Voc T5 — Resolvedor operativo con lenguaje de análisis",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText: [
        "Hoy rindo mejor cuando tengo que resolver fallas, ajustar procesos, ordenar prioridad y hacer que la operación salga sin trabarse.",
        "De chico me gustaba arreglar cosas, ordenar tareas y hacer que algo que no funcionaba volviera a salir.",
        "Me atraían los mecanismos, los procesos concretos y cómo mejorar algo que estaba trabado.",
        "Siempre termino resolviendo fallas, ajustando procesos, priorizando, mejorando la operación y haciendo que salga sin trabarse.",
        "Mi rol natural es resolvedor, operador y organizador práctico.",
        "Dejé en pausa ideas más grandes por quedarme sosteniendo crisis y operación.",
        "Apago incendios sobre la marcha y uso menos de lo que podría en diseño operativo más estable.",
        "Tengo criterio y análisis, sí, pero puestos al servicio de ejecución, pasos concretos y mejora de procesos.",
      ].join(" "),
      expectedPrimaryFamily: "technical_builder",
      acceptableFamilies: [
        "technical_builder",
        "system_designer",
        "analytical_strategist",
      ],
      rivalFamilies: ["analytical_strategist", "system_designer"],
      keyHumanLanguage: [
        "resolver fallas",
        "ajustar procesos",
        "hacer que la operación salga",
        "arreglar cosas",
        "procesos concretos",
        "mejorar algo trabado",
        "resolvedor",
        "apago incendios",
      ],
      missingCuesDetected: [
        "quality: strong_contrastive_case",
        "learningTier: validated_clear",
        "influenceWeight: high",
        "secondaryFamily: system_designer",
        "tertiaryFamily: analytical_strategist",
        "el análisis está subordinado a ejecución concreta y destrabe operativo",
      ],
      verdict: "learning_candidate",
      lesson:
        "Caso contrastivo fuerte para Technical Builder. Las palabras de análisis no deben arrastrar a estratega o diseñador cuando la acción dominante es destrabar, ejecutar y hacer funcionar la operación.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_voc_t6_cultural_explorer_storyteller_overread_warning_001",
      title: "Voc T6 — Curador de contextos que escribe, no narrador central",
      source: "manual_synthetic",
      language: "es",
      region: "LatAm",
      inputText: [
        "Trabajo en algo estable, pero mi interés persistente está en leer historia, cultura, procesos sociales y conectar contextos.",
        "Desde chico acumulaba autores, épocas, mapas y relaciones entre temas que parecían lejanos.",
        "Me interesaban la historia, la cultura, los idiomas y la conexión entre contextos distintos.",
        "En la escuela me atraían Historia, Literatura y Filosofía.",
        "Siempre termino investigando contextos, comparando procesos sociales, relacionando autores y escribiendo síntesis para ordenar ideas de distintos campos.",
        "Aprendí mucho y conecté mucho, pero pocas veces convertí eso en una trayectoria visible.",
        "Mi curiosidad cultural sigue viva, pero no siempre se traduce en una dirección laboral reconocible.",
        "Escribo para ordenar y sintetizar, no porque mi impulso central sea construir relato o voz propia.",
      ].join(" "),
      expectedPrimaryFamily: "cultural_explorer",
      acceptableFamilies: ["cultural_explorer", "educator_interpreter"],
      rivalFamilies: ["creative_storyteller", "educator_interpreter"],
      keyHumanLanguage: [
        "leer historia y cultura",
        "conectar contextos",
        "acumulaba autores y épocas",
        "relaciones entre temas",
        "investigando contextos",
        "comparando procesos sociales",
        "escribiendo síntesis",
        "escribo para ordenar y sintetizar",
      ],
      missingCuesDetected: [
        "calibration_only",
        "expected_cultural_explorer",
        "observed_creative_storyteller",
        "storyteller_overread_warning",
        "cultural_explorer_underread_warning",
        "writing_is_instrumental_not_core_storytelling",
        "do_not_use_as_validated_case",
        "quality: misread_warning",
        "learningTier: calibration_warning",
      ],
      actualResult: {
        corePattern: "creative_storyteller",
        resultType: "clear_direction",
        familyScores: [
          {
            topFamily: "creative_storyteller",
            score: 0.51,
            confidence: 0.64,
          },
          {
            family: "educator_interpreter",
            score: 0.32,
            confidence: 0.59,
          },
          {
            family: "cultural_explorer",
            score: 0.19,
            confidence: 0.36,
          },
        ],
      },
      verdict: "borderline",
      lesson:
        "Caso de advertencia de calibración: la escritura puede ser instrumental para ordenar y sintetizar contextos, sin que eso implique un impulso narrativo central. No usar este caso como validación fuerte.",
      shouldInfluenceFutureCases: false,
    },
    {
      id: "learned_voc_t7_creative_storyteller_cultural_background_001",
      title: "Voc T7 — Narradora con fondo cultural, no curadora",
      source: "manual_synthetic",
      language: "es",
      region: "LatAm",
      inputText: [
        "Pienso enfoque y referencias culturales, pero donde realmente rindo es escribiendo, editando, construyendo mensajes y dando claridad narrativa.",
        "Desde chica escribía, nombraba cosas con precisión y armaba relatos para que otros entendieran mejor una escena.",
        "Me fascinaban la literatura, la voz, los mensajes, el tono y cómo construir relato con lenguaje.",
        "En la escuela me atraían Lengua, Literatura e Historia.",
        "Siempre termino escribiendo, editando, nombrando, construyendo relato y dándole forma verbal a ideas complejas para volverlas comunicables.",
        "Mi rol natural es narrar, editar y construir mensajes.",
        "Usé mucho lenguaje funcional o comercial y no siempre pude sostener mi veta más narrativa como eje principal.",
        "Escribo y sintetizo todos los días, pero no siempre desde una dirección reconocible de contenido o relato.",
        "La cultura me nutre, pero no me define como exploradora sino como constructora de voz, mensajes y relato claro.",
      ].join(" "),
      expectedPrimaryFamily: "creative_storyteller",
      acceptableFamilies: ["creative_storyteller"],
      rivalFamilies: [
        "cultural_explorer",
        "public_communicator",
        "educator_interpreter",
      ],
      keyHumanLanguage: [
        "escribiendo y editando",
        "claridad narrativa",
        "armaba relatos",
        "voz y tono",
        "construir relato con lenguaje",
        "forma verbal a ideas complejas",
        "narrar y construir mensajes",
        "constructora de voz",
      ],
      missingCuesDetected: [
        "validated_clear_case",
        "creative_storyteller",
        "cultural_background_not_primary",
        "narrative_voice_core",
        "public_communicator_absence",
        "educator_interpreter_absence",
        "quality: strong_clear_case",
        "learningTier: validated_clear",
      ],
      actualResult: {
        corePattern: "creative_storyteller",
        resultType: "clear_direction",
        familyScores: [
          {
            topFamily: "creative_storyteller",
            score: 0.76,
            confidence: 0.81,
          },
          {
            family: "public_communicator",
            score: 0,
            confidence: 0.51,
          },
          {
            family: "educator_interpreter",
            score: 0,
            confidence: 0.51,
          },
        ],
      },
      verdict: "learning_candidate",
      lesson:
        "Caso validado: la cultura funciona como insumo, pero el núcleo dominante es voz narrativa, edición y construcción de mensaje con forma verbal propia.",
      shouldInfluenceFutureCases: true,
    },
    {
      id: "learned_voc_t8_institutional_operator_diplomatic_frontier_001",
      title: "Voc T8 — Operador institucional, no mediador relacional",
      source: "manual_synthetic",
      language: "es",
      region: "LatAm",
      inputText: [
        "Hoy rindo mejor cuando tengo que cuidar vínculos institucionales, leer marcos formales y alinear intereses entre áreas o sectores.",
        "Desde chico me interesaban los ámbitos donde había normas, roles, intereses cruzados y necesidad de coordinación fina.",
        "Me atraía entender cómo se mueve una estructura y por dónde conviene empujar sin chocar al pedo.",
        "Siempre termino leyendo el marco, entendiendo con quién hay que hablar y ubicando qué paso falta para que algo avance dentro del sistema.",
        "Uso mi capacidad para sostener equilibrios, pero no siempre en una dirección propia con más expansión.",
        "No puedo hacer cambios bruscos; necesito sostener reputación y estabilidad.",
        "Mis activos son negociación institucional, lectura política, orden estructural y coordinación formal.",
      ].join(" "),
      expectedPrimaryFamily: "institutional_operator",
      acceptableFamilies: ["institutional_operator", "diplomatic_social_connector"],
      rivalFamilies: ["diplomatic_social_connector", "commercial_connector"],
      keyHumanLanguage: [
        "vínculos institucionales",
        "marcos formales",
        "alinear intereses",
        "normas y roles",
        "coordinación fina",
        "leer el marco",
        "avance dentro del sistema",
        "reputación y estabilidad",
      ],
      missingCuesDetected: [
        "frontier_support",
        "institutional_operator",
        "diplomatic_social_connector",
        "very_close_race",
        "formal_structure_dominates",
        "relational_bridge_secondary",
        "useful_for_negative_evidence_judge",
        "quality: useful_frontier_case",
        "learningTier: validated_frontier",
      ],
      actualResult: {
        corePattern: "institutional_operator / diplomatic_social_connector",
        resultType: "clear_direction",
        familyScores: [
          {
            topFamily: "institutional_operator",
            score: 0.71,
            confidence: 0.74,
          },
          {
            secondFamily: "diplomatic_social_connector",
            score: 0.69,
            confidence: 0.78,
          },
          {
            isVeryCloseRace: true,
            shouldAvoidSingleClearClaim: true,
          },
        ],
      },
      verdict: "learning_candidate",
      lesson:
        "Caso de frontera útil: puede ganar el perfil institucional cuando dominan reglas, estructura, reputación y avance formal, aunque exista una señal relacional fuerte como segunda familia.",
      shouldInfluenceFutureCases: true,
    },

    // =========================================================================
    // FAILURE REFERENCE CASES
    // Casos que el motor determinístico no resuelve bien. Sirven como señales
    // de alerta y guía para futuros casos similares.
    // =========================================================================

    {
      id: "fail_ref_system_designer_parches",
      title: "FAIL REF: System designer confundido con technical_builder por lenguaje práctico",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "En el trabajo vivo viendo que muchos problemas se arreglan con parches. Se soluciona lo urgente, pero nadie mira que el sistema está armado para volver a fallar. Me pasa con procesos, equipos, planillas, circuitos. Empiezo mirando una falla y termino pensando cómo habría que rediseñar todo.",
      expectedPrimaryFamily: "system_designer",
      acceptableFamilies: ["system_designer", "analytical_strategist"],
      rivalFamilies: ["technical_builder"],
      keyHumanLanguage: [
        "sistema armado para volver a fallar",
        "rediseñar todo",
        "parches",
        "nadie mira la estructura",
        "apagando incendios",
      ],
      missingCuesDetected: [
        "rediseñar todo debe pesar como señal de system_designer no de technical_builder",
        "parches + estructura = diseño sistémico no ejecución técnica",
      ],
      verdict: "failed",
      lesson:
        "Cuando alguien habla de parches, rediseñar, y la estructura que genera el problema, es system_designer. El vocabulario práctico (arreglar, falla) confunde al motor con technical_builder.",
      shouldInfluenceFutureCases: true,
      difficultyTier: "failure_reference",
      failureContext: {
        whatWentWrong: "technical_builder gana por vocabulario práctico (arreglar, falla, funcionar) pese a que la intención es rediseñar sistemas",
        confusedWith: ["technical_builder"],
        missingSignals: ["system_ordering", "structural_reasoning"],
        correctedFamily: "system_designer",
        humanVerified: true,
      },
    },
    {
      id: "fail_ref_creative_storyteller_compressed",
      title: "FAIL REF: Creative storyteller con compresión que no se detecta como compressed_life",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Trabajo en algo que me sostiene pero que no tiene casi nada que ver conmigo. Cumplo, respondo, llego a fin de mes, pero siento que una parte muy mía quedó guardada en un cajón. Cada tanto vuelvo a escribir escenas, frases, recuerdos. No lo hago de manera ordenada ni profesional, pero cuando aparece siento que ahí hay algo más vivo.",
      expectedPrimaryFamily: "creative_storyteller",
      acceptableFamilies: ["creative_storyteller", "artistic_creator"],
      rivalFamilies: ["public_communicator"],
      keyHumanLanguage: [
        "guardada en un cajón",
        "parte muy mía",
        "escribir escenas",
        "algo más vivo",
        "no tiene nada que ver conmigo",
      ],
      missingCuesDetected: [
        "guardada en un cajón es señal de compresión creativa fuerte",
        "el contraste entre sostenimiento funcional y vitalidad creativa debe detectarse",
      ],
      verdict: "failed",
      lesson:
        "Cuando alguien describe su trabajo como funcional-vacío y luego menciona momentos de escritura/creación como lo más vivo, es compressed_life + creative_storyteller. La compresión es tan fuerte como la dirección.",
      shouldInfluenceFutureCases: true,
      difficultyTier: "failure_reference",
      failureContext: {
        whatWentWrong: "El motor no detecta compressed_life cuando la compresión se expresa con metáforas (cajón, arrinconado) en lugar de vocabulario directo",
        confusedWith: ["public_communicator"],
        missingSignals: ["narrative_creation", "compression_signals"],
        correctedFamily: "creative_storyteller",
        humanVerified: true,
      },
    },
    {
      id: "fail_ref_operational_organizer_burnout",
      title: "FAIL REF: Operational organizer en burnout funcional no detectado como compressed_life",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Sigo funcionando, que es casi lo peor. Cumplo, ordeno, resuelvo, tapo agujeros, hago que las cosas salgan, pero cada vez con menos resto por dentro. En todos los trabajos termino siendo la persona que sabe qué falta y cómo sacar algo adelante aunque falten recursos. Mi capacidad está usada en modo supervivencia.",
      expectedPrimaryFamily: "operational_organizer",
      acceptableFamilies: ["operational_organizer", "resource_steward"],
      rivalFamilies: ["technical_builder", "system_designer"],
      keyHumanLanguage: [
        "sigo funcionando",
        "modo supervivencia",
        "cada vez con menos resto",
        "tapo agujeros",
        "sacar algo adelante",
      ],
      missingCuesDetected: [
        "modo supervivencia es compresión clara",
        "menos resto por dentro = desgaste sin colapso",
        "funcionar sin entusiasmo = compressed_life",
      ],
      verdict: "failed",
      lesson:
        "El burnout funcional (sigo cumpliendo pero vacío por dentro) es compressed_life. La persona tiene operational_organizer como familia pero la está usando en modo supervivencia, no en modo construcción.",
      shouldInfluenceFutureCases: true,
      difficultyTier: "failure_reference",
      failureContext: {
        whatWentWrong: "El motor detecta clear_direction porque las señales de organización son fuertes, pero no reconoce que están siendo usadas en modo desgaste",
        confusedWith: ["technical_builder"],
        missingSignals: ["compression_signals", "burnout_functional"],
        correctedFamily: "operational_organizer",
        humanVerified: true,
      },
    },
    {
      id: "fail_ref_empathic_guide_overload",
      title: "FAIL REF: Empathic guide sobrecargado por sostener a otros",
      source: "manual_synthetic",
      language: "es",
      region: "Argentina",
      inputText:
        "Siempre fui la persona a la que todos le cuentan todo. Me buscan cuando están mal, cuando necesitan que alguien los escuche sin juzgar. Pero llegué a un punto donde estoy agotado de absorber dolor ajeno sin espacio para mí. Lo que hago importa pero me está vaciando.",
      expectedPrimaryFamily: "empathic_guide",
      acceptableFamilies: ["empathic_guide"],
      rivalFamilies: ["diplomatic_social_connector"],
      keyHumanLanguage: [
        "todos le cuentan todo",
        "escuche sin juzgar",
        "absorber dolor ajeno",
        "me está vaciando",
        "sin espacio para mí",
      ],
      missingCuesDetected: [
        "absorber dolor ajeno sin espacio para mí es compresión del guía empático",
        "vaciamiento por exceso de escucha = compressed_life del empathic_guide",
      ],
      verdict: "failed",
      lesson:
        "Un empathic_guide que dice estar vaciándose por absorber demasiado dolor ajeno es compressed_life, no clear_direction. La compresión viene del exceso, no de la falta de identidad vocacional.",
      shouldInfluenceFutureCases: true,
      difficultyTier: "failure_reference",
      failureContext: {
        whatWentWrong: "El motor ve señales de empathic_guide fuertes y declara clear_direction, pero no detecta que la persona está desbordada — es compressed_life por sobreuso",
        confusedWith: ["diplomatic_social_connector"],
        missingSignals: ["compression_by_overuse", "empathic_fatigue"],
        correctedFamily: "empathic_guide",
        humanVerified: true,
      },
    },
    {
      id: "learned_estefi_pioneer_admin_compressed_frontier_001",
      title:
        "Pionera: admin remoto + infancia creativa no deben tapar escucha, investigación y vida comprimida",
      source: "real_user",
      language: "es",
      region: "Argentina",
      inputText:
        "Trabajo remoto como office manager para una empresa extranjera. Me valoran y la paga es buena, pero no siento que sea mi vocación; tengo miedo de morir sin descubrir para qué vine. Estudié psicología pero no era mi vocación; hoy me gusta escuchar, dar consejos y ayudar, ya no desde un lugar tan pasivo. De chica me gustaban juegos de mesa, la imaginación, la música y soñar con guitarra, pero mi historia adulta pesa más: conecté con mucha gente, apostolado, idiomas. Llevo años siguiendo instrucciones como empleada responsable. Me ven alegre, buena amiga, de confianza. Dejé amigos, deportes y estudio por carga familiar, matrimonio difícil, ingresos justos con tres hijos. Quiero tiempo, amistades, deporte, ideas de negocio y apoyo de mi marido. Me comprimió no animarme por miedo al dinero, al ridículo o a no saber cómo. Soñé con embajada pero en provincia no conocía el sistema; cuando pude informarme ya pasé el límite de edad para diplomacia. También me hubiera gustado investigación tipo SIDE o FBI: resolver misterios, atar cabos, teorías, investigar personas.",
      expectedPrimaryFamily: "empathic_guide",
      acceptableFamilies: [
        "empathic_guide",
        "scientific_investigator",
        "diplomatic_social_connector",
        "educator_interpreter",
        "commercial_connector",
      ],
      rivalFamilies: [
        "artistic_creator",
        "technical_builder",
        "operational_organizer",
      ],
      keyHumanLanguage: [
        "escuchar",
        "dar consejos",
        "ayudar",
        "estudié psicología",
        "office manager",
        "no es mi vocación",
        "miedo de morir sin descubrir",
        "embajada",
        "diplomacia",
        "investigación",
        "SIDE",
        "FBI",
        "resolver misterios",
        "atar cabos",
        "investigar personas",
        "tres hijos",
        "ingresos justos",
        "dejé amigos",
        "dejé deportes",
        "ideas de negocios",
        "baja autoestima",
        "seguir instrucciones",
        "empleada responsable",
        "juegos de mesa",
        "imaginación",
      ],
      missingCuesDetected: [
        "rol administrativo remoto no debe cerrar la lectura en operational_organizer ni technical_builder",
        "infancia creativa o juegos de mesa no deben empujar artistic_creator por encima de escucha/ayuda adulta",
        "psicología + consejos + confianza social deben sostener empathic_guide",
        "SIDE/FBI/atar cabos/investigar personas deben activar scientific_investigator",
        "embajada/diplomacia postergada debe activar diplomatic_social_connector",
        "carga familiar + renuncias + miedo a animarse = compressed_life o frontera prudente, no clear_direction cerrado",
        "ideas de negocios pueden sumar commercial_connector sin ser familia dominante",
      ],
      actualResult: {
        corePattern: "Artistic Creator / Technical Builder",
        resultType: "clear_direction",
        familyScores: [],
      },
      verdict: "learning_candidate",
      lesson:
        "Cuando conviven rol administrativo remoto, infancia con juegos/imaginación/música y una historia adulta de escucha, consejo, investigación de misterios y diplomacia postergada con vida muy comprimida, la lectura debe ser frontera entre Empathic Guide, Scientific Investigator y Diplomatic Social Connector — no cerrar en Artistic Creator / Technical Builder ni en clear_direction.",
      shouldInfluenceFutureCases: true,
      difficultyTier: "frontier",
      failureContext: {
        whatWentWrong:
          "El sistema cerró Artistic Creator / Technical Builder por señales creativas de infancia y trabajo administrativo, ignorando escucha/ayuda adulta, investigación (SIDE/FBI, atar cabos) y embajada postergada, y trató el caso como clear_direction.",
        confusedWith: ["artistic_creator", "technical_builder"],
        missingSignals: [
          "adult_listening_and_advice",
          "investigation_mystery_drive",
          "postponed_diplomacy_dream",
          "compressed_life_family_marriage",
          "admin_role_is_survival_not_vocation",
        ],
        correctedFamily: "empathic_guide",
        humanVerified: true,
      },
    },
];