import type { HumanAffinityDefinition } from "../types/humanAffinity";

export const HUMAN_AFFINITIES: HumanAffinityDefinition[] = [
  {
    id: "narrative_creation",
    label: "Narrative Creation",
    cluster: "expression",
    summary:
      "Tiende a convertir experiencia, ideas o hechos en relato, texto o pieza expresiva con forma propia.",
    detectionHints: [
      "escribir",
      "escribiendo",
      "texto",
      "relato",
      "historia",
      "narrar",
      "narración",
      "narracion",
      "darle forma",
      "dar forma",
      "volverlo texto",
      "volverla texto",
      "contarlo",
      "contar algo",
      "pieza",
      "escena",
      "guion",
      "voz narrativa",
      "construir relato",
      "editar un texto",
    ],
    confusableWith: ["public_expression", "meaning_synthesis"],
    likelyDomains: ["work", "art", "civic", "community"],
    relatedContributionModes: ["clarifies", "frames", "communicates"],
    relatedFlourishingConditions: [
      "espacio para escribir o editar",
      "audiencia real",
      "autonomía expresiva",
    ],
  },
  {
    id: "public_expression",
    label: "Public Expression",
    cluster: "expression",
    summary:
      "Impulso a expresarse ante otros y sostener presencia discursiva en espacios públicos.",
    detectionHints: [
      "hablar en publico",
      "hablar en público",
      "decir lo que pienso",
      "opinar en publico",
      "opinar en público",
      "posteos",
      "posteos con bajada",
      "voz publica",
      "voz pública",
      "programa",
      "radio",
      "salir al aire",
      "audiencia",
      "microfono",
      "micrófono",
      "conducir",
      "conducción",
      "conduccion",
      "intervenir publicamente",
      "intervenir públicamente",
    ],
    confusableWith: ["performance_presence", "audience_activation"],
    likelyDomains: ["work", "civic", "community", "art"],
    relatedContributionModes: ["broadcasts", "voices", "activates"],
    relatedFlourishingConditions: [
      "audiencia presente",
      "canal de expresión",
      "temas con resonancia pública",
    ],
  },
  {
    id: "editorial_framing",
    label: "Editorial Framing",
    cluster: "expression",
    summary:
      "Capacidad de fijar enfoque, tono y marco interpretativo para ordenar temas ante una audiencia.",
    detectionHints: [
      "enfoque",
      "bajada",
      "angulo",
      "ángulo",
      "marco",
      "tono",
      "fijar postura",
      "ordenar un tema",
      "ordenar el tema",
      "jerarquizar temas",
      "linea editorial",
      "línea editorial",
      "dar interpretación",
      "dar interpretacion",
      "columna de opinion",
      "columna de opinión",
    ],
    confusableWith: ["agenda_detection", "meaning_synthesis"],
    likelyDomains: ["work", "civic", "community"],
    relatedContributionModes: ["frames", "interprets", "positions"],
    relatedFlourishingConditions: [
      "espacio de criterio propio",
      "temas complejos",
      "libertad para enfocar",
    ],
  },
  {
    id: "audience_activation",
    label: "Audience Activation",
    cluster: "expression",
    summary:
      "Tendencia a movilizar atención, reacción o participación de una audiencia.",
    detectionHints: [
      "movilizar audiencia",
      "activar audiencia",
      "enganchar a la gente",
      "generar reacción",
      "generar respuesta",
      "hacer ruido",
      "mover algo",
      "la gente reacciono",
      "la gente reaccionó",
      "rebote",
      "circulación pública",
      "circulacion publica",
      "se compartio",
      "se compartió",
    ],
    confusableWith: ["public_expression", "influence_negotiation"],
    likelyDomains: ["work", "civic", "community", "art"],
    relatedContributionModes: ["mobilizes", "engages", "amplifies"],
    relatedFlourishingConditions: [
      "feedback visible",
      "audiencia activa",
      "canales de difusión",
    ],
  },
  {
    id: "pattern_analysis",
    label: "Pattern Analysis",
    cluster: "analysis",
    summary:
      "Capacidad de detectar regularidades, inconsistencias o conexiones estructurales no obvias.",
    detectionHints: [
      "patrones",
      "inconsistencia",
      "inconsistencias",
      "no cierra",
      "ver que no cierra",
      "comparar escenarios",
      "comparar caminos",
      "ver variables",
      "leer estructura",
      "veo estructuras",
      "detectar regularidades",
      "detectar criterio",
      "comparar alternativas",
      "que se esta dejando afuera",
      "que se está dejando afuera",
    ],
    confusableWith: ["system_ordering", "meaning_synthesis"],
    likelyDomains: ["work", "civic", "community"],
    relatedContributionModes: ["detects", "compares", "clarifies"],
    relatedFlourishingConditions: [
      "problemas complejos",
      "tiempo para pensar",
      "acceso a información",
    ],
  },
  {
    id: "meaning_synthesis",
    label: "Meaning Synthesis",
    cluster: "analysis",
    summary:
      "Tendencia a unir piezas sueltas en una visión con sentido, comprensión o interpretación más amplia.",
    detectionHints: [
      "dar sentido",
      "unir piezas",
      "sintetizar",
      "conectar ideas",
      "relacionar ideas",
      "relacionar autores",
      "ver como dialogan",
      "ver cómo dialogan",
      "entender procesos",
      "juntar referencias",
      "explicar el fondo",
      "integrar cosas distintas",
      "hacer una sintesis",
      "hacer una síntesis",
    ],
    confusableWith: ["editorial_framing", "pattern_analysis"],
    likelyDomains: ["work", "civic", "community", "art"],
    relatedContributionModes: ["synthesizes", "interprets", "integrates"],
    relatedFlourishingConditions: [
      "material rico",
      "espacio reflexivo",
      "temas abiertos",
    ],
  },
  {
    id: "system_ordering",
    label: "System Ordering",
    cluster: "analysis",
    summary:
      "Impulso a organizar complejidad en marcos, mapas, secuencias o procesos comprensibles.",
    detectionHints: [
      "ordenar procesos",
      "armar estructura",
      "dar marco",
      "mapear opciones",
      "poner en sistema",
      "organizar complejidad",
      "arquitectura",
      "secuencia",
      "marco de trabajo",
      "armar un sistema",
      "mapear un problema",
      "ordenar el proceso",
      "estructurar una decision",
      "estructurar una decisión",
    ],
    confusableWith: ["pattern_analysis", "practical_execution"],
    likelyDomains: ["work", "civic", "community"],
    relatedContributionModes: ["organizes", "structures", "maps"],
    relatedFlourishingConditions: [
      "caos informativo",
      "problemas abiertos",
      "necesidad de ordenar",
    ],
  },
  {
    id: "strategic_projection",
    label: "Strategic Projection",
    cluster: "analysis",
    summary:
      "Tendencia a pensar escenarios, movimientos y consecuencias futuras antes de actuar.",
    detectionHints: [
      "escenarios",
      "por donde conviene",
      "por dónde conviene",
      "que puede pasar",
      "qué puede pasar",
      "consecuencias",
      "movimiento",
      "estrategia",
      "proyeccion",
      "proyección",
      "antes de decidir",
      "pensar un camino",
      "pensar alternativas",
      "leer hacia adelante",
    ],
    confusableWith: ["pattern_analysis", "agenda_detection"],
    likelyDomains: ["work", "civic", "community"],
    relatedContributionModes: ["anticipates", "projects", "orients"],
    relatedFlourishingConditions: [
      "decisiones relevantes",
      "margen para proyectar",
      "contexto dinámico",
    ],
  },
  {
    id: "evidence_validation",
    label: "Evidence Validation",
    cluster: "analysis",
    summary:
      "Necesidad de corroborar, verificar o basar lectura en evidencia antes de cerrar una conclusión.",
    detectionHints: [
      "corroborar",
      "verificar",
      "evidencia",
      "datos",
      "confirmar con datos",
      "probar con evidencia",
      "validar",
      "validacion",
      "validación",
      "chequear",
      "comprobar",
    ],
    confusableWith: ["pattern_analysis", "conceptual_abstraction"],
    likelyDomains: ["work", "civic", "community"],
    relatedContributionModes: ["verifies", "tests", "grounds"],
    relatedFlourishingConditions: [
      "información disponible",
      "espacio para contrastar",
      "criterio de validación",
    ],
  },
  {
    id: "conceptual_abstraction",
    label: "Conceptual Abstraction",
    cluster: "analysis",
    summary:
      "Facilidad para pensar en conceptos, categorías, marcos e ideas generales.",
    detectionHints: [
      "concepto",
      "conceptual",
      "categorias",
      "categorías",
      "modelo",
      "marco conceptual",
      "principio",
      "idea abstracta",
      "pensar en grande",
      "nivel conceptual",
      "abstraccion",
      "abstracción",
    ],
    confusableWith: ["meaning_synthesis", "pattern_analysis"],
    likelyDomains: ["work", "civic", "community", "art"],
    relatedContributionModes: ["abstracts", "models", "categorizes"],
    relatedFlourishingConditions: [
      "preguntas abiertas",
      "espacio intelectual",
      "material para modelar",
    ],
  },
  {
    id: "empathic_attunement",
    label: "Empathic Attunement",
    cluster: "relational",
    summary:
      "Capacidad de sintonizar con estados internos ajenos y leer matices humanos finos.",
    detectionHints: [
      "escuchar sin invadir",
      "escuchar bien",
      "escuchar de verdad",
      "preguntas justas",
      "uno a uno",
      "bajar un cambio",
      "lo que le pasa",
      "lo que siente",
      "poner en palabras lo que siente",
      "ayudar a poner en palabras",
      "hecho un nudo",
      "hecho bolsa",
      "registrar al otro",
      "ordenar lo que le pasa",
    ],
    confusableWith: ["care_orientation", "trust_building"],
    likelyDomains: ["work", "community", "family", "spiritual"],
    relatedContributionModes: ["accompanies", "clarifies", "contains"],
    relatedFlourishingConditions: [
      "espacio uno a uno",
      "tiempo para comprender",
      "confianza",
    ],
  },
  {
    id: "restorative_support",
    label: "Restorative Support",
    cluster: "relational",
    summary:
      "Tendencia a sostener procesos de alivio, reordenamiento interno o reparación subjetiva.",
    detectionHints: [
      "acompañar procesos",
      "acompañar un proceso",
      "contener",
      "estar para alguien",
      "ayudar a ordenar lo confuso",
      "bajar ansiedad",
      "aliviar",
      "sostener en un momento dificil",
      "sostener en un momento difícil",
      "dar espacio",
      "sin meter presion",
      "sin meter presión",
    ],
    confusableWith: ["empathic_attunement", "care_orientation"],
    likelyDomains: ["work", "community", "family", "spiritual"],
    relatedContributionModes: ["supports", "restores", "stabilizes"],
    relatedFlourishingConditions: [
      "procesos delicados",
      "confianza relacional",
      "tiempo de acompañamiento",
    ],
  },
  {
    id: "care_orientation",
    label: "Care Orientation",
    cluster: "relational",
    summary:
      "Inclinación a cuidar, sostener y hacerse cargo de cómo están otros o un espacio humano.",
    detectionHints: [
      "cuidar",
      "poner el hombro",
      "estar para",
      "sostener a otros",
      "estar cuando hace falta",
      "cuidar el clima",
      "que el otro este bien",
      "que el otro esté bien",
      "acompañar sin soltar",
      "hacerse cargo del cuidado",
    ],
    confusableWith: ["restorative_support", "group_reading"],
    likelyDomains: ["work", "community", "family", "spiritual"],
    relatedContributionModes: ["cares", "holds", "supports"],
    relatedFlourishingConditions: [
      "vínculos de confianza",
      "responsabilidad humana",
      "espacios donde cuidar importa",
    ],
  },
  {
    id: "trust_building",
    label: "Trust Building",
    cluster: "relational",
    summary:
      "Capacidad de generar confianza, cercanía y base relacional estable para que otros se abran o colaboren.",
    detectionHints: [
      "generar confianza",
      "la gente se abre",
      "me cuentan cosas",
      "confian en mi",
      "confían en mí",
      "sostener vinculo",
      "sostener vínculo",
      "la gente se acerca",
      "dar confianza",
      "crear un clima de confianza",
      "hacer sentir parte",
    ],
    confusableWith: ["empathic_attunement", "social_coordination"],
    likelyDomains: ["work", "community", "family"],
    relatedContributionModes: ["bonds", "stabilizes", "enables"],
    relatedFlourishingConditions: [
      "tiempo vincular",
      "continuidad relacional",
      "entornos donde la confianza pesa",
    ],
  },
  {
    id: "group_reading",
    label: "Group Reading",
    cluster: "relational",
    summary:
      "Lectura del clima, la pertenencia y la dinámica de un grupo o comunidad.",
    detectionHints: [
      "clima",
      "clima colectivo",
      "leer el grupo",
      "como esta el grupo",
      "cómo está el grupo",
      "pertenencia",
      "que no se enfrie",
      "que no se enfríe",
      "que la gente no se disperse",
      "sostener un grupo",
      "vida grupal",
      "circulacion entre personas",
      "circulación entre personas",
      "sostener comunidad",
    ],
    confusableWith: ["social_coordination", "care_orientation"],
    likelyDomains: ["work", "community", "civic"],
    relatedContributionModes: ["reads climate", "holds belonging", "stabilizes groups"],
    relatedFlourishingConditions: [
      "grupos vivos",
      "interacción sostenida",
      "espacios donde el clima importa",
    ],
  },
  {
    id: "relational_bridge_building",
    label: "Relational Bridge Building",
    cluster: "relational",
    summary:
      "Tendencia a conectar personas, áreas o posiciones separadas para habilitar vínculo y circulación.",
    detectionHints: [
      "conectar partes",
      "hablar con uno y con otro",
      "puente entre areas",
      "puente entre áreas",
      "acercar posiciones",
      "conectar gente",
      "entre partes",
      "entre areas",
      "entre áreas",
      "juntar sectores",
      "hacer de puente",
      "ida y vuelta entre partes",
    ],
    confusableWith: ["social_coordination", "conflict_mediation"],
    likelyDomains: ["work", "civic", "community"],
    relatedContributionModes: ["connects", "links", "bridges"],
    relatedFlourishingConditions: [
      "diversidad de actores",
      "espacios de cruce",
      "interdependencia",
    ],
  },
  {
    id: "social_coordination",
    label: "Social Coordination",
    cluster: "relational",
    summary:
      "Facilidad para ordenar interacción entre varios actores y sostener funcionamiento colectivo o grupal.",
    detectionHints: [
      "coordinar grupos",
      "coordinar entre personas",
      "ordenar la interaccion",
      "ordenar la interacción",
      "hacer funcionar entre varios",
      "sostener funcionamiento colectivo",
      "articular actores",
      "coordinar una movida",
      "hacer circular entre personas",
      "ordenar cruces",
      "acomodar entre varios",
    ],
    confusableWith: ["relational_bridge_building", "institutional_navigation"],
    likelyDomains: ["work", "civic", "community"],
    relatedContributionModes: ["coordinates", "aligns", "stabilizes"],
    relatedFlourishingConditions: [
      "múltiples actores",
      "responsabilidades compartidas",
      "necesidad de orden relacional",
    ],
  },
  {
    id: "conflict_mediation",
    label: "Conflict Mediation",
    cluster: "relational",
    summary:
      "Inclinación a bajar tensiones, traducir posiciones y encontrar cauce cuando hay fricción entre partes.",
    detectionHints: [
      "mediar",
      "bajar tension",
      "bajar tensión",
      "destrabar entre partes",
      "malos entendidos",
      "evitar choque",
      "se sienten a hablar",
      "hacer que avance",
      "cuando hay gente cruzada",
      "areas que no se entienden",
      "áreas que no se entienden",
      "ordenar la friccion",
      "ordenar la fricción",
    ],
    confusableWith: ["social_coordination", "influence_negotiation"],
    likelyDomains: ["work", "civic", "community", "family"],
    relatedContributionModes: ["mediates", "de-escalates", "reorders"],
    relatedFlourishingConditions: [
      "tensión real",
      "intereses cruzados",
      "necesidad de cauce",
    ],
  },
  {
    id: "practical_execution",
    label: "Practical Execution",
    cluster: "execution",
    summary:
      "Capacidad de llevar cosas a la realidad concreta y hacer que avancen.",
    detectionHints: [
      "hacer que salga",
      "resolver lo concreto",
      "ejecutar",
      "concretar",
      "llevar a la practica",
      "llevar a la práctica",
      "sacar adelante",
      "hacerlo andar",
      "poner en marcha",
      "que se haga",
    ],
    confusableWith: ["operational_rhythm", "initiative_drive"],
    likelyDomains: ["work", "community", "family"],
    relatedContributionModes: ["executes", "implements", "delivers"],
    relatedFlourishingConditions: [
      "objetivos concretos",
      "margen de acción",
      "prioridades claras",
    ],
  },
  {
    id: "technical_assembly",
    label: "Technical Assembly",
    cluster: "execution",
    summary:
      "Capacidad de meter mano, ajustar, reparar o ensamblar para que algo funcione mejor.",
    detectionHints: [
      "meter mano",
      "arreglar",
      "reparar",
      "ajustar",
      "dejar funcionando",
      "hacer con las manos",
      "armar y desarmar",
      "resolver una falla",
      "resolver fallas",
      "acomodar algo material",
      "que no falle",
    ],
    confusableWith: ["practical_execution", "resource_optimization"],
    likelyDomains: ["work", "home", "craft"],
    relatedContributionModes: ["repairs", "adjusts", "builds"],
    relatedFlourishingConditions: [
      "problemas concretos",
      "herramientas o materiales",
      "margen de intervención técnica",
    ],
  },
  {
    id: "resource_optimization",
    label: "Resource Optimization",
    cluster: "execution",
    summary:
      "Tendencia a mejorar uso de recursos, tiempo, energía o procesos para que rindan mejor.",
    detectionHints: [
      "optimizar",
      "mejor uso",
      "eficiencia",
      "aprovechar recursos",
      "ahorrar tiempo",
      "ordenar recursos",
      "hacerlo mas eficiente",
      "hacerlo más eficiente",
      "mejorar rendimiento",
    ],
    confusableWith: ["system_ordering", "operational_rhythm"],
    likelyDomains: ["work", "community", "home"],
    relatedContributionModes: ["optimizes", "streamlines", "improves"],
    relatedFlourishingConditions: [
      "procesos mejorables",
      "restricción de recursos",
      "necesidad de eficiencia",
    ],
  },
  {
    id: "operational_rhythm",
    label: "Operational Rhythm",
    cluster: "execution",
    summary:
      "Sensibilidad para prioridades, tiempos, secuencia operativa y continuidad de una operación.",
    detectionHints: [
      "a tiempo",
      "prioridades",
      "ritmo",
      "urgente",
      "operacion",
      "operación",
      "que no se trabe",
      "que no se caiga",
      "sostener la operacion",
      "sostener la operación",
      "orden operativo",
      "tiempos de trabajo",
    ],
    confusableWith: ["practical_execution", "social_coordination"],
    likelyDomains: ["work", "community"],
    relatedContributionModes: ["paces", "prioritizes", "sustains operations"],
    relatedFlourishingConditions: [
      "flujo operativo",
      "responsabilidad concreta",
      "necesidad de continuidad",
    ],
  },
  {
    id: "craft_precision",
    label: "Craft Precision",
    cluster: "execution",
    summary:
      "Gusto por el detalle, la prolijidad y el trabajo bien terminado.",
    detectionHints: [
      "detalle",
      "prolijidad",
      "bien hecho",
      "terminar bien",
      "precision",
      "precisión",
      "fino",
      "cuidar terminacion",
      "cuidar terminación",
      "no dejarlo a medias",
    ],
    confusableWith: ["technical_assembly", "aesthetic_sensitivity"],
    likelyDomains: ["work", "craft", "art", "home"],
    relatedContributionModes: ["refines", "polishes", "finishes well"],
    relatedFlourishingConditions: [
      "tiempo para hacer bien",
      "estándar de calidad",
      "trabajo concreto",
    ],
  },
  {
    id: "initiative_drive",
    label: "Initiative Drive",
    cluster: "agency",
    summary:
      "Tendencia a activar, empezar y empujar movimiento sin esperar permiso.",
    detectionHints: [
      "tome la iniciativa",
      "tomé la iniciativa",
      "arranque yo",
      "arranqué yo",
      "lo impulse",
      "lo impulsé",
      "no espere",
      "no esperé",
      "empece algo",
      "empecé algo",
      "fui el que arranco",
      "fui el que arrancó",
    ],
    confusableWith: ["practical_execution", "decision_ownership"],
    likelyDomains: ["work", "civic", "community"],
    relatedContributionModes: ["starts", "pushes", "activates"],
    relatedFlourishingConditions: [
      "espacio de autonomía",
      "necesidad de arranque",
      "baja burocracia",
    ],
  },
  {
    id: "decision_ownership",
    label: "Decision Ownership",
    cluster: "agency",
    summary:
      "Capacidad de definir, asumir criterio y hacerse cargo de una decisión dentro de una estructura.",
    detectionHints: [
      "tomar decisiones",
      "hacerme cargo",
      "definir",
      "bancar la decision",
      "bancar la decisión",
      "asumir la decision",
      "asumir la decisión",
      "ser quien decide",
      "sostener una decision",
      "sostener una decisión",
    ],
    confusableWith: ["initiative_drive", "strategic_projection"],
    likelyDomains: ["work", "civic", "community"],
    relatedContributionModes: ["decides", "owns", "defines"],
    relatedFlourishingConditions: [
      "responsabilidad real",
      "margen de decisión",
      "estructura con consecuencias",
    ],
  },
  {
    id: "influence_negotiation",
    label: "Influence Negotiation",
    cluster: "agency",
    summary:
      "Capacidad de persuadir, negociar o mover posiciones de otros para cerrar acuerdos o habilitar avance.",
    detectionHints: [
      "negociar",
      "convencer",
      "mover posiciones",
      "cerrar acuerdo",
      "cerrar algo",
      "incidir",
      "persuadir",
      "destrabar acuerdo",
      "hacer que acepten",
      "encontrar punto de acuerdo",
    ],
    confusableWith: ["conflict_mediation", "audience_activation"],
    likelyDomains: ["work", "civic", "community"],
    relatedContributionModes: ["persuades", "negotiates", "influences"],
    relatedFlourishingConditions: [
      "interacción política o institucional",
      "intereses en juego",
      "margen de incidencia",
    ],
  },
  {
    id: "institutional_navigation",
    label: "Institutional Navigation",
    cluster: "agency",
    summary:
      "Lectura y manejo de reglas, marcos, autoridades y estructuras institucionales.",
    detectionHints: [
      "institucional",
      "instituciones",
      "estructura formal",
      "dentro de la estructura",
      "reglas",
      "autoridades",
      "quien decide",
      "quién decide",
      "por donde conviene empujar",
      "por dónde conviene empujar",
      "poder formal",
      "marco formal",
      "dentro del sistema formal",
    ],
    confusableWith: ["social_coordination", "agenda_detection"],
    likelyDomains: ["work", "civic", "community"],
    relatedContributionModes: ["navigates", "positions", "operates"],
    relatedFlourishingConditions: [
      "instituciones activas",
      "reglas complejas",
      "interfaz con poder formal",
    ],
  },
  {
    id: "agenda_detection",
    label: "Agenda Detection",
    cluster: "agency",
    summary:
      "Capacidad de notar qué tema importa, crece o estructura el escenario colectivo.",
    detectionHints: [
      "agenda",
      "tema del momento",
      "tema central",
      "eje del momento",
      "lo que importa",
      "lo que crece",
      "clima publico",
      "clima público",
      "tendencia publica",
      "tendencia pública",
      "priorizar temas",
    ],
    confusableWith: ["editorial_framing", "strategic_projection"],
    likelyDomains: ["work", "civic", "community"],
    relatedContributionModes: ["detects", "prioritizes", "surfaces"],
    relatedFlourishingConditions: [
      "contexto dinámico",
      "atención pública",
      "necesidad de priorizar temas",
    ],
  },
  {
    id: "protective_instinct",
    label: "Protective Instinct",
    cluster: "agency",
    summary:
      "Impulso a proteger, defender o ponerse al frente cuando alguien o algo valioso queda expuesto.",
    detectionHints: [
      "defender",
      "proteger",
      "salir por alguien",
      "no dejar solo",
      "cuidar a otros",
      "poner el cuerpo",
      "bancar una causa",
      "bancar a alguien",
      "salir a enfrentar",
    ],
    confusableWith: ["care_orientation", "civic_conflict_engagement"],
    likelyDomains: ["civic", "community", "family", "work"],
    relatedContributionModes: ["protects", "defends", "stands up"],
    relatedFlourishingConditions: [
      "situaciones de exposición",
      "valores en juego",
      "causas con rostro humano",
    ],
  },
  {
    id: "civic_conflict_engagement",
    label: "Civic Conflict Engagement",
    cluster: "agency",
    summary:
      "Inclinación a intervenir en asuntos colectivos, tensiones públicas o causas con impulso de incidencia.",
    detectionHints: [
      "politica",
      "política",
      "reclamo",
      "injusticia",
      "causa",
      "protesta",
      "tema publico",
      "tema público",
      "debate publico",
      "debate público",
      "conflicto social",
      "vida civica",
      "vida cívica",
      "meterme cuando algo esta mal",
      "meterme cuando algo está mal",
    ],
    confusableWith: ["public_expression", "influence_negotiation"],
    likelyDomains: ["civic", "community", "work"],
    relatedContributionModes: ["intervenes", "advocates", "mobilizes"],
    relatedFlourishingConditions: [
      "temas colectivos",
      "espacio público",
      "causas con fricción real",
    ],
  },
  {
    id: "curiosity_depth",
    label: "Curiosity Depth",
    cluster: "exploration",
    summary:
      "Deseo sostenido de entender en profundidad y no quedarse en superficie.",
    detectionHints: [
      "profundizar",
      "entender a fondo",
      "ir al fondo",
      "seguir investigando",
      "me obsesiona entender",
      "lectura profunda",
      "quiero entender mejor",
      "no quedarme en la superficie",
    ],
    confusableWith: ["exploratory_drive", "evidence_validation"],
    likelyDomains: ["work", "art", "civic", "community"],
    relatedContributionModes: ["investigates", "deepens", "understands"],
    relatedFlourishingConditions: [
      "tiempo de profundización",
      "material complejo",
      "libertad de exploración",
    ],
  },
  {
    id: "exploratory_drive",
    label: "Exploratory Drive",
    cluster: "exploration",
    summary:
      "Impulso a recorrer, probar, averiguar y meterse en territorios o temas nuevos.",
    detectionHints: [
      "explorar",
      "recorrer",
      "averiguar",
      "probar",
      "salir a conocer",
      "moverme",
      "investigar por mi cuenta",
      "meterme en temas nuevos",
      "ir a ver",
      "conocer lugares",
    ],
    confusableWith: ["curiosity_depth", "initiative_drive"],
    likelyDomains: ["work", "travel", "culture", "community"],
    relatedContributionModes: ["explores", "discovers", "opens paths"],
    relatedFlourishingConditions: [
      "margen de movimiento",
      "entornos nuevos",
      "posibilidad de descubrir",
    ],
  },
  {
    id: "adaptive_reframing",
    label: "Adaptive Reframing",
    cluster: "exploration",
    summary:
      "Capacidad de cambiar encuadre, reinterpretar y abrir una lectura alternativa de una situación.",
    detectionHints: [
      "verlo de otra manera",
      "cambiar enfoque",
      "reencuadrar",
      "reinterpretar",
      "darle otra lectura",
      "nuevo marco",
      "otra perspectiva",
      "cambiar el encuadre",
    ],
    confusableWith: ["meaning_synthesis", "editorial_framing"],
    likelyDomains: ["work", "community", "civic"],
    relatedContributionModes: ["reframes", "reinterprets", "opens options"],
    relatedFlourishingConditions: [
      "problemas abiertos",
      "contextos cambiantes",
      "margen para reformular",
    ],
  },
  {
    id: "teaching_impulse",
    label: "Teaching Impulse",
    cluster: "exploration",
    summary:
      "Tendencia espontánea a explicar, traducir o ayudar a comprender.",
    detectionHints: [
      "explicar",
      "enseñar",
      "traducir",
      "hacer entender",
      "bajar a tierra",
      "bajar algo complicado",
      "dar ejemplos",
      "guiar a otros",
      "que el resto entienda",
      "explicarlo claro",
      "traducir dificultad",
    ],
    confusableWith: ["narrative_creation", "meaning_synthesis"],
    likelyDomains: ["work", "community", "family", "spiritual"],
    relatedContributionModes: ["explains", "translates", "guides understanding"],
    relatedFlourishingConditions: [
      "interacción educativa",
      "material complejo para traducir",
      "personas aprendiendo",
    ],
  },
  {
    id: "aesthetic_sensitivity",
    label: "Aesthetic Sensitivity",
    cluster: "expression",
    summary:
      "Sensibilidad a forma, tono, atmósfera, belleza o coherencia estética.",
    detectionHints: [
      "estetica",
      "estética",
      "tono",
      "forma",
      "atmósfera",
      "visual",
      "belleza",
      "detalle visual",
      "sensibilidad estetica",
      "sensibilidad estética",
    ],
    confusableWith: ["craft_precision", "narrative_creation"],
    likelyDomains: ["art", "work", "community"],
    relatedContributionModes: ["shapes tone", "refines form", "senses aesthetics"],
    relatedFlourishingConditions: [
      "espacio creativo",
      "material sensible",
      "libertad formal",
    ],
  },
  {
    id: "performance_presence",
    label: "Performance Presence",
    cluster: "expression",
    summary:
      "Comodidad o intensidad al ponerse al frente, sostener escena o expresar con presencia corporal/discursiva.",
    detectionHints: [
      "escena",
      "presencia",
      "poner el cuerpo",
      "estar al frente",
      "conducir",
      "voz",
      "frente a gente",
      "sostener una escena",
      "poner la cara",
    ],
    confusableWith: ["public_expression", "audience_activation"],
    likelyDomains: ["art", "work", "civic"],
    relatedContributionModes: ["presents", "holds presence", "embodies message"],
    relatedFlourishingConditions: [
      "espacios visibles",
      "audiencia presente",
      "margen de presencia personal",
    ],
  },
];

export const HUMAN_AFFINITY_MAP = Object.fromEntries(
  HUMAN_AFFINITIES.map((affinity) => [affinity.id, affinity]),
);